### DISCUSSION TITLE
New manifest - uninstall fails to find installed package

### DISCUSSION THREAD

**Discussion by kriswilk** [microsoft/winget-pkgs#110506] [Q&A]
I'm hoping someone can point out what I'm missing here. I've created a simple (?) manifest that will install correctly, but refuses to uninstall. I get the message:

```
PS C:\Users\kris\manifests\p\PelikanSoftware\priPrinter> winget uninstall --manifest .\6.9.0.2541\
Found priPrinter [PelikanSoftware.priPrinter]
No installed package found matching input criteria.
```

For reference, the application appears in ARP like this...

![image](https://github.com/microsoft/winget-pkgs/assets/382436/8dc54c0c-e522-48ca-9175-2c3f04c1a706)

...and the contents of the manifest files are:

`PelikanSoftware.priPrinter.installer.yaml`
```
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: PelikanSoftware.priPrinter
PackageVersion: 6.9.0.2541
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://www.priprinter.com/files/priPrinterSetup.exe
  InstallerSha256: 0624672E8B4FFCF0C55C1D95CBE7D56AA67942CBDEBBB522617315934D0E05E2
ManifestType: installer
ManifestVersion: 1.4.0
```

`PelikanSoftware.priPrinter.locale.en-US.yaml`
```
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: PelikanSoftware.priPrinter
PackageVersion: 6.9.0.2541
PackageLocale: en-US
Publisher: Pelikan Software
PackageName: priPrinter
License: Commercial
Copyright: Copyright © 2023 Pelikan Software
ShortDescription: priPrinter
ManifestType: defaultLocale
ManifestVersion: 1.4.0
```

`PelikanSoftware.priPrinter.yaml`
```
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: PelikanSoftware.priPrinter
PackageVersion: 6.9.0.2541
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
```

The `PackageName` and `PackageVersion` should match up, but WinGet disagrees. What could be the problem?

**Comment by Trenly** [comment]
Using your manifest, I get the following output from my test script-
```
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.Admin setting enabled.

--> Installing the Manifest 6.9.0.2541

Found priPrinter [PelikanSoftware.priPrinter] Version 6.9.0.2541
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.priprinter.com/files/priPrinterSetup.exe
  ██████████████████████████████  3.97 MB / 3.97 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName DisplayVersion Publisher            ProductCode
----------- -------------- ---------            -----------
priPrinter  6.9.0.2541     Pelikan Software KFT priPrinter
```

A few things stand out to me -
1) The publisher in the manifest should probably be `Pelikan Software KFT` - This won't solve the issue, but does help correlation
2) This is a new package, so there isn't any existing correlation information in the repo - This is likely related to the issue, but probably doesn't have a ton of effect
3) If you add the ProductCode to the installer manifest, the uninstall works just fine

```
Installers:
- Architecture: x86
  InstallerUrl: https://www.priprinter.com/files/priPrinterSetup.exe
  InstallerSha256: 0624672E8B4FFCF0C55C1D95CBE7D56AA67942CBDEBBB522617315934D0E05E2
  ProductCode: priPrinter
```

It seems that local manifest uninstall doesn't use the same correlation as the normal uninstall flow, and I'm not sure why it isn't finding the package, but adding the product code should fix it
