### DISCUSSION TITLE
SandBox - Installer failed with exit code: 2147516547

### DISCUSSION THREAD

**Discussion by lin-ycv** [microsoft/winget-pkgs#134109] [Q&A] [answered]
I'm trying to create a winget package, but on the sandbox test, it keeps failing
`Installer failed with exit code: 2147516547`
I'm running with Administrator previleges

![Screenshot 2024-01-15 175926](https://github.com/microsoft/winget-pkgs/assets/60565737/afa23679-d8d8-402e-b2ba-19315a40a1a8)

this is my YAML
```yaml
PackageIdentifier: linycv.EverythingPowerToys
PackageVersion: 0.77.0
PackageLocale: en-US
Publisher: linycv
PackageName: EverythingPowerToys
PackageUrl: "https://github.com/lin-ycv/EverythingPowerToys"
License: Unlicensed
ShortDescription: Everything search plugin for PowerToys Run.
Tags:
- "Everything"
- "PowerToys"
- "Run"
- "Search"
- "Launcher"
- "PowerToysRun"
- "EverythingPowerToys"
Installers: 
 - Architecture: x64
   InstallerType: exe
   InstallerSwitches:
     Silent: /s
     SilentWithProgress: /s
   InstallModes:
   - silent
   InstallerUrl: https://github.com/lin-ycv/EverythingPowerToys/releases/download/installer/EverythingPTRunInstaller.exe
   InstallerSha256: a668f1787f41146236e41936e5a3b7a27e6e9e45889727bb1a6acd3b80fbc8d1
ManifestType: singleton
ManifestVersion: 1.0.0
```

Can anyone tell me why? the exe file runs fine locally, but not in sandbox.
