### DISCUSSION TITLE
Should all manifests be in English?

### DISCUSSION THREAD

**Discussion by latere-a-latere** [microsoft/winget-pkgs#1509] [General]
Using @donid's handy dandy [WingetRepoBrowser](https://github.com/donid/WingetRepoBrowser) tool I discovered that the packages `Tencent.TencentMeeting` and `Tencent.TencentVideo` both have Mandarin descriptions. 

While I understand how this happened, Tencent being a Chinese company primarily catering to Chinese users, I was wondering if this should be corrected to an English translation and if all future manifests should be in English. (at least until support for multi-language manifests is added)

These are currently the only two packages that are non-english and I'd rather tackle this early on than later when we have thousands of packages.

**Comment by OfficialEsco** [comment]
Late answer is better then never
Does the validation fail if you use this? The ManifestSpec dosn't say its NOT supported so...

```
Localization:
  - Language: es-MX
    Description: Text to display for es-MX
    Homepage: https://github.com/microsoft/msix-packaging/es-MX
    LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE-es-MX
```
