### DISCUSSION TITLE
Script to get AppsAndFeaturesEntries!

### DISCUSSION THREAD

**Discussion by jedieaston** [microsoft/winget-pkgs#38882] [Show and tell]
Happy holidays all! 🎅

I made a little present for everybody: a script that will fill AppsAndFeaturesEntries for all of the installer entries in a manifest. I haven't tested it a bunch yet, but I figured it was important to get something out there now that there's functionality in the client depending on it (https://github.com/microsoft/winget-cli/pull/1796 among others).

The script executes each installer entry in a Sandbox, using `winget install`'s newish command line arguments to force the matching algorithm down a certain path. This means you need a build of winget that is newer than the one in releases to make this work. Fear not, I thought of that (I built it locally, and VS includes a handy PowerShell script to trust the certificate. Works great in a sandbox.)

This script has a lot more work that needs to be done to it to make it work in 99% of cases instead of 80% or so, but it will get us started. 

I've attached a zip file with the script and wingetdev build. To use it, run `.\Add-ARPEntries.ps1 <path to manifest you want to add values to>` (and make sure you have Windows Sandbox enabled).  I'll probably make a repo (or at least a gist) for this eventually.

[generatearp.zip](https://github.com/microsoft/winget-pkgs/files/7839232/generatearp.zip)

Edit (1/3): Fixed incompatibility with PowerShell 7.
Edit (1/10): Fixed a path whoopsie.

**Comment by vedantmgoyal9** [comment]
> I made a little present for everybody

Developers have best gifts to give 😂

**Comment by OfficialEsco** [comment]
Soooo, what if i don't use Hyper-V? 🤔
Is there no easy way to do this without Sandbox? Would be amazing for YamlCreate, validation pipeline and Wingetcreate

edit:
I'm guessing this kinda works like PRTest or Levvies PR test script, so would it add this for VC++2015-2019x64?
```
AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual C++ 2019 X64 Additional Runtime - 14.29.30135
    Publisher:  Microsoft Corporation
    DisplayVersion: 14.29.30135
    ProductCode: '{34DB4181-0770-4B5A-B561-68758A077B0F}'
  - DisplayName: Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.29.30135
    Publisher:  Microsoft Corporation
    DisplayVersion: 14.29.30135
    ProductCode: '{40118CD9-A805-400C-864E-041A5B5C01B0}'
  - DisplayName: Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30135
    Publisher:  Microsoft Corporation
    DisplayVersion: 14.29.30135.0
    ProductCode: '{fa7f6d52-f85e-48ef-8f56-a37268aa5772}'
```

**Reply by jedieaston** [reply]
You could do it via Docker for Windows containers. I'm going to work on doing that next, GH Actions runners can run Windows Docker containers so we could do it that way. 

Also, that output is pretty much right. Here's what the script gives me:

```
AppsAndFeaturesEntries:
  - DisplayName: Microsoft Visual C++ 2019 X64 Additional Runtime - 14.29.30135
    DisplayVersion: 14.29.30135
    Publisher: Microsoft Corporation
    ProductCode: '{34DB4181-0770-4B5A-B561-68758A077B0F}'
  - DisplayName: Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.29.30135
    DisplayVersion: 14.29.30135
    Publisher: Microsoft Corporation
    ProductCode: '{40118CD9-A805-400C-864E-041A5B5C01B0}'
  - DisplayName: Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30135
    DisplayVersion: 14.29.30135.0
    Publisher: Microsoft Corporation
    ProductCode: '{fa7f6d52-f85e-48ef-8f56-a37268aa5772}'
```
