### DISCUSSION TITLE
Silent-Switches for nested installers

### DISCUSSION THREAD

**Discussion by borque** [microsoft/winget-pkgs#95089] [Q&A] [answered]
Hello!
I have created a 1.4-manifest with a nested inno-installer. Though I specified this type, it is not silenced automatically.
So my question is, where and how to integrate the silent-switches for nested installers into 1.4-manifests?
Thanks!

**Comment by Trenly** [comment, marked as answer]
I believe you add them like you would for a normal installer.
```
InstallerType: zip
NestedInstallerType: inno
InstallerSwitches:
  Silent: <switch>
  SilentWithProgress: <switch>
InstallerUrl: <url>
InstallerSha256: <sha>
```
