### ISSUE TITLE
Foxit Reader hash fails and installer seems to silently hang

### ISSUE THREAD

**Issue by bushidocodes** [microsoft/winget-pkgs#10072]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

`winget install Foxit.FoxitReader` reports a hash mismatch. 

If the `--force` flag is used, the installer hangs silently in the background.

# Steps to reproduce

`winget install Foxit.FoxitReader`

# Expected behavior

Expected to install cleanly

# Actual behavior

Installer hangs silently in background and software does not install

# Environment

```
Windows Package Manager v0.2.10771 Preview
Copyright (c) Microsoft Corporation. All rights reserved.
Windows: Windows.Desktop v10.0.19042.870
Package: Microsoft.DesktopAppInstaller v1.11.10771.0
```

**Comment by jedieaston** [comment]
I think I just resolved this in #10087, once it merges, can you try this again?

**Comment by bushidocodes** [comment]
Hi @jedieaston. Just gave it a shot and got the following:
```
❯ winget install Foxit.FoxitReader
Found FoxitReader [Foxit.FoxitReader]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foxitsoftware.com/downloads/latest.php?product=Foxit-Reader&platform=Windows&package_type=exe&language=L10N
  ██████████████████████████████  95.4 MB / 95.4 MB
Installer hash does not match; to override this check use --force
```
And with show:

```
❯ winget show Foxit.FoxitReader                                                                                                                                                                                  Found FoxitReader [Foxit.FoxitReader]
Version: latest
Publisher: Foxit
Description: Industry’s Most Powerful PDF Reader.
Homepage: https://www.foxitsoftware.com/pdf-editor/
License: 2020 © Foxit Software Incorporated. All rights reserved.
Installer:
  Type: Exe
  Download Url: https://www.foxitsoftware.com/downloads/latest.php?product=Foxit-Reader&platform=Windows&package_type=exe&language=L10N
  SHA256: 69728969a674271794843694b6588aadb8f4517d7eefd16bd22309c1e8ae8cb5
```

I've only been using winget for a day or two, so please let me know if I'm missing something.
