### ISSUE TITLE
[Package Request]: kontext

### ISSUE THREAD

**Issue by thedatabaseme** [microsoft/winget-pkgs#102536]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/orbatschow/kontext/releases/tag/v1.1.0
Publisher: Orbatschow
Package Name: kontext
Package Identifier: orbatschow.kontext
Description: Kontext is a single binary application, that takes yet another approach on kubeconfig management.
Package Version: 1.1.0
Installer URL: https://github.com/orbatschow/kontext/releases/download/v1.1.0/kontext_Windows_x86_64.zip

Hello,

I tried to create the multifile-manifest for the above named package like so;

Version manifest
```yaml
PackageIdentifier: orbatschow.kontext
PackageVersion: 1.1.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.0.0
```

Locale manifest:
```yaml
PackageIdentifier: orbatschow.kontext
PackageVersion: 1.1.0
PackageLocale: en-US
Publisher: Orbatschow
PublisherUrl: https://orbat.sh
Author: Orbatschow
PackageName: kontext
PackageUrl: https://github.com/orbatschow/kontext/
License: Apache-2.0
LicenseUrl: https://github.com/orbatschow/kontext/blob/master/LICENSE
ShortDescription: Declarative kubeconfig management within a single binary.
Description: Kontext is a single binary application, that takes yet another approach on kubeconfig management.
Tags:
- cli
- devops-tools
- golang
- kubernetes
- context
- kubeconfig
- portable
- terminal
ReleaseNotesUrl: https://github.com/orbatschow/kontext/releases/tag/v1.1.0
ManifestType: defaultLocale
ManifestVersion: 1.0.0
```

Installer manifest:
```yaml
PackageIdentifier: orbatschow.kontext
PackageVersion: 1.1.0
InstallerLocale: en-US
InstallerType: zip
Commands:
- kontext
ReleaseDate: 2023-04-10
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: kontext.exe
    PortableCommandAlias: kontext
  InstallerUrl: https://github.com/orbatschow/kontext/releases/download/v1.1.0/kontext_Windows_x86_64.zip
  InstallerSha256: e1f74a8487338060112238fcca2b056a7ab3e814ea7c2a1b2adcc157751e2a9c
- Architecture: arm
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: kontext.exe
    PortableCommandAlias: kontext
  InstallerUrl: https://github.com/orbatschow/kontext/releases/download/v1.1.0/kontext_Windows_arm64.zip
  InstallerSha256: f8d658aeafb254019f7af6d659cd0615f8a3d9aab6f0eb3ff5f4f3679f4b69eb
ManifestType: installer
ManifestVersion: 1.0.0
```

When trying to validate this manifests with `winget validate`, I get the following errors:

```
Manifest Warning: Unknown field. [ReleaseDate]
Manifest Warning: Unknown field. [ReleaseNotesUrl]
Manifest Warning: Unknown field. [NestedInstallerFiles]
Manifest Warning: Unknown field. [NestedInstallerType]
Manifest Warning: Unknown field. [NestedInstallerFiles]
Manifest Warning: Unknown field. [NestedInstallerType]
Manifest Error: Invalid field value. [InstallerType]
Manifest Error: Required field missing. [NestedInstallerType]
Manifest Error: Required field missing. [NestedInstallerFiles]
Manifest Error: Only one entry for NestedInstallerFiles can be specified for non-portable InstallerTypes. [NestedInstallerFiles]
Manifest Error: Invalid field value. [InstallerType]
Manifest Error: Required field missing. [NestedInstallerType]
Manifest Error: Required field missing. [NestedInstallerFiles]
Manifest Error: Only one entry for NestedInstallerFiles can be specified for non-portable InstallerTypes. [NestedInstallerFiles]
```

It seems to me, that winget can't work with the installertype `zip`. But I thought, that this is implemented within winget 1.4.x.
Can you advise on how the error might lie?

Kind Regards
Philip
