### ISSUE TITLE
Add Deno 1.8.3

### ISSUE THREAD

**Issue by pranavb** [microsoft/winget-pkgs#10476]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier: Deno.deno
PackageVersion: 1.8.3
PackageLocale: en-US
Publisher: Deno
PackageName: deno
License: MIT
ShortDescription: Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.
Installers: 
 - Architecture: x64
   InstallerType: zip # Blocked on github.com/microsoft/winget-cli/issues/140 
   InstallerUrl: https://github.com/denoland/deno/releases/download/v1.8.3/deno-x86_64-pc-windows-msvc.zip
   InstallerSha256: FCE64FBEDC922429C26C9D2302F5B1E2B0ABE95567A8766B8E759C7BD15DFA4D
ManifestType: singleton
ManifestVersion: 1.0.0
```
