### ISSUE TITLE
Handbreak

### ISSUE THREAD

**Issue by musm** [microsoft/winget-pkgs#11248]
# Package Requested

Handbreak

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      # 1.3.3
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           # The HandBrake Team 
PackageName:         # package name (example: "Windows Terminal")
License:             # GNU General Public License (GPL) Version 2
ShortDescription:    # open-source video transcoder 
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
