### ISSUE TITLE
Spacedesk Driver (Server)

### ISSUE THREAD

**Issue by AlJohri** [microsoft/winget-pkgs#11902]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:  Datronicsoft‬.SpacedeskDriver
PackageVersion: 0.9.95
PackageLocale: en-US
Publisher: datronicsoft
PackageName: spacedesk
License:  # license is here: https://spacedesk.net/##box_431
ShortDescription:  Network Display Multi Monitor Driver (Server)
Installers: 
 - Architecture:  x64
   InstallerType: msi
   InstallerUrl:  https://spacedesk.net/downloads/spacedesk_driver_Win_10_64_v0995_BETA.msi
   InstallerSha256: 832f2fa7d0fc6ffd3b51e626a656a721dcc24178adc8e1079c4bfc731ca25276
ManifestType: singleton
ManifestVersion: 1.0.0
```

Notes:

- Download page: https://spacedesk.net/##box_434
- Latest Installer URL which redirects to MSI: https://spacedesk.net/downloadidd64
