### ISSUE TITLE
[Package Request]: 

### ISSUE THREAD

**Issue by freddyboy1974** [microsoft/winget-pkgs#121595]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://plugin.fileopen.com/all.aspx
Publisher: FileOpen Systems Inc.
Package Name: FileOpen Plug-in Installer for Windows
Description: FileOpen Systems provides a set of free plug-ins and viewers that can be used to access documents encrypted with the FileOpen software.
Package Version: Build 998
Installer URL: https://plugin.fileopen.com/current/FileOpenInstaller64.msi

**Comment by Dragon1573** [comment]
@freddyboy1974 I'm glad to help. Inspecting installer files from the [download page](https://plugin.fileopen.com/), the following file is generated.

<details>
<summary><code>manifests/f/FileOpen/FileOpen/3.0.176.998/FileOpen.FileOpen.installer.yaml</code></summary>

```yaml
# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: FileOpen.FileOpen
PackageVersion: 3.0.176.998
Installers:
  - InstallerUrl: https://plugin.fileopen.com/current/FileOpenInstaller.exe
    Architecture: x64
    InstallerType: inno
    InstallerSha256: F469734BC576A00E113BC43B1B1A13DE3C74F5370C5B9DB8B9289BD9CF8AAC31
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Adobe.Acrobat.Reader.64-bit
  - InstallerUrl: https://plugin.fileopen.com/current/FileOpenInstaller64.msi
    Architecture: x64
    InstallerType: wix
    InstallerSha256: EB1A5F76997B39171A9D812B5F55F681E05F080F34D873FF0B3C4EB9129C6350
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Adobe.Acrobat.Reader.64-bit
ManifestType: installer
ManifestVersion: 1.5.0
```

</details>

![image](https://github.com/microsoft/winget-pkgs/assets/49941141/3a1d0293-7344-483a-a1bc-a25fc344ed55)

When running tests in Windows Sandbox, the plug-in installation will fail when neither Acrobat Reader or DC Pro 9 is installed, so I add `Adobe.Acrobat.Reader.64-bit` as `PackageDependencies`.

Despite from configuring `PackageDependencies`, it also allow users to provide Acrobat Reader or DC Pro 9 externally. If user previously installed Acrobat DC Pro, the above manifest will ignore it and install a brand new Reader for the user.

@SpecterShell Is this package worth submitting to the repository? Thank you.
