### ISSUE TITLE
[Package Issue]: SweetScape.010Editor

### ISSUE THREAD

**Issue by k-bock** [microsoft/winget-pkgs#125999]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installer for 010 Editor 14 installs the 32-bit variant regardless of the running system. The actual installer package is incorrectly the same for x86 and x64 architectures

```
Installers:
- Architecture: x86
  InstallerUrl: https://download.sweetscape.com/010EditorWin32Installer14.0.exe
  InstallerSha256: 11D96FA10DF0F8E6ADD3509E03B963C398A190890F0EA45D8E56C4DD77CBEAA9
- Architecture: x64
  InstallerUrl: https://download.sweetscape.com/010EditorWin32Installer14.0.exe
  InstallerSha256: 11D96FA10DF0F8E6ADD3509E03B963C398A190890F0EA45D8E56C4DD77CBEAA9
```

### Steps to reproduce

- Use x64 Windows
- Install 010 Editor 14

### Actual behavior

x86 is being installed

### Expected behavior

x64 version should be installed

### Environment

```raw
Windows-Paket-Manager v1.6.2771
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22631.2506
Systemarchitektur: X64
Paket: Microsoft.DesktopAppInstaller v1.21.2771.0

WinGet-Verzeichnisse
-----------------------------------------------------------------------------------------------------------------------
Protokolle                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Benutzereinstellungen                        %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Verzeichnis für portierbare Links (Benutzer) %LOCALAPPDATA%\Microsoft\WinGet\Links
Portables Linkverzeichnis (Computer)         C:\Program Files\WinGet\Links
Portierbarer Paketstamm (Benutzer)           %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portierbarer Paketstamm                      C:\Program Files\WinGet\Packages
Portierbares Paketstamm (x86)                C:\Program Files (x86)\WinGet\Packages
Installationsprogrammdownloads               %USERPROFILE%\Downloads

Links
-----------------------------------------------------------------------------------------
Datenschutzerklärung              https://aka.ms/winget-privacy
Lizenzvereinbarung                https://aka.ms/winget-license
Hinweise von Drittanbietern       https://aka.ms/winget-3rdPartyNotice
Startseite                        https://aka.ms/winget
Windows Store-Nutzungsbedingungen https://www.microsoft.com/en-us/storedocs/terms-of-sale

Administratoreinstellung                  Status
-----------------------------------------------------
LocalManifestFiles                        Deaktiviert
BypassCertificatePinningForMicrosoftStore Deaktiviert
InstallerHashOverride                     Deaktiviert
LocalArchiveMalwareScanOverride           Deaktiviert
```
