### ISSUE TITLE
[Package Issue]: Orange-OpenSource.Hurl

### ISSUE THREAD

**Issue by lepapareil** [microsoft/winget-pkgs#134245]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the Winget client.

### Category of the issue

Other

### Brief description of your issue

When updating with `wingetcreate update` I get this error message (like https://github.com/microsoft/winget-create/issues/118):

```
Each new installation URL must match an existing installer based on architecture, installation type, and scope. The following installers failed to match an existing installer: Multiple matches found for X86 Nullsoft installer detected from the URL: https://github.com/Orange-OpenSource/hurl/releases/download/4.2.0/hurl-4.2.0-x86_64-pc-windows-msvc-installer.exe"
```

Perhaps `x86_` is in conflict with the `architecture: x64` on the manifest, but package name is inherited from Rustlang target platform, I don't want to change this, it's the builder reference.

### Steps to reproduce

```
./wingetcreate update --submit --token <github token> --urls https://github.com/Orange-OpenSource/hurl/releases/download/4.2.0/hurl-4.2.0-x86_64-pc-windows-msvc-installer.exe --version 4.2.0 Orange-OpenSource.Hurl
```

### Actual behavior

```
Each new installation URL must match an existing installer based on architecture, installation type, and scope. The following installers failed to match an existing installer: Multiple matches found for X86 Nullsoft installer detected from the URL: https://github.com/Orange-OpenSource/hurl/releases/download/4.2.0/hurl-4.2.0-x86_64-pc-windows-msvc-installer.exe"
```

### Expected behavior

I want `wingetcreate update` to succeed as like before 😄.

### Environment

```
WingetCreateCLI 1.5.7.0
```

```
PackageIdentifier: Orange-OpenSource.Hurl
PackageVersion: 4.1.0
MinimumOSVersion: 10.0.0.0
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl-4.1.0-x86_64-pc-windows-msvc-installer.exe
  InstallerSha256: 896B38711CA43E2DCFE3F5A5E96954E62A76F78C5700E846BD367F6696B07317
ManifestType: installer
ManifestVersion: 1.1.0
```
