### ISSUE TITLE
Nomacs 

### ISSUE THREAD

**Issue by leochras** [microsoft/winget-pkgs#13817]
# Nomacs

Manifest:

```YAML
PackageIdentifier:   # nomacs.nomacs
PackageVersion:      # 3.16.224
PackageLocale:       # en-US
Publisher:           # nomacs
PackageName:         # nomacs
License:             # GPL 3.0
ShortDescription:    # nomacs - Image Lounge
Installers: 
 - Architecture:     # x64
   InstallerType:    # exe/msi/zip
   InstallerUrl:     # https://github.com/nomacs/nomacs/releases/tag/3.16.224
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
