### ISSUE TITLE
Roccat Swarm

### ISSUE THREAD

**Issue by derkrasseleo** [microsoft/winget-pkgs#13847]
# Package Requested

Manifest:

This program can't be installed because it comes as a .zip:

```YAML
PackageIdentifier:   # ROCCATA.Swarm
PackageVersion:      # 1.9389
PackageLocale:       # en_US
Publisher:           # ROCCAT
PackageName:         # ROCCAT Swarm
License:             # Copyright
ShortDescription:    # Swarm is used to customize, personalize and keep your ROCCAT® devices up-to-date.
Installers: 
 - Architecture:     # x64
   InstallerType:    # .zip
   InstallerUrl:     # https://api.roccat-neon.com/device/Support/Software/Download/230
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
