### ISSUE TITLE
Apache Netbeans

### ISSUE THREAD

**Issue by derkrasseleo** [microsoft/winget-pkgs#13844]
# Package Requested

Manifest:

This installation is possible on local machines, where a JDK exists, but not when tested with the Sandbox Script:

```YAML
PackageIdentifier:   # Apache.Netbeans
PackageVersion:      # 12.3.0.0
PackageLocale:       # en-US
Publisher:           # Apache
PackageName:         # Netbeans
License:             # Apache-2.0 (https://github.com/apache/netbeans/blob/master/LICENSE)
ShortDescription:    # Development Environment, Tooling Platform and Application Framework.
Installers: 
 - Architecture:     # x64
   InstallerType:    # EXE
   InstallerUrl:     # https://mirror.klaus-uwe.me/apache/netbeans/netbeans/12.3/Apache-NetBeans-12.3-bin-windows-x64.exe
   InstallerSha256:  # 1784356E557E441DF9FFFA3514D46FDFD79F66750958923F1E45AC2B4AF9A488
ManifestType: singleton
ManifestVersion: 1.0.0
```
