### ISSUE TITLE
Add Microsoft.OpenJDK.16 GA build

### ISSUE THREAD

**Issue by d3vel0per** [microsoft/winget-pkgs#13984]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   Microsoft.OpenJDK.16
PackageVersion:      16.0.1
PackageLocale:       en-US
Publisher:           Microsoft
PackageName:         Microsoft OpenJDK 16
License:            GPL2 with Classpath Exception.
ShortDescription:    The Microsoft Build of OpenJDK is a new no-cost long-term supported distribution and Microsoft's new way to collaborate and contribute to the Java ecosystem.
Installers: 
 - Architecture:     x64
   InstallerType:    msi
   InstallerUrl:     https://aka.ms/download-jdk/microsoft-jdk-16.0.1.9.1-windows-x64.msi
   InstallerSha256:  356d2bfc6e39dd30e358f4ad33dd29817758d0ac354327ea41064a9a67a49344
ManifestType: singleton
ManifestVersion: 1.0.0
```
