### ISSUE TITLE
Update Microsoft.OpenJDK.11 to GA status (Remove Preview from description)

### ISSUE THREAD

**Issue by d3vel0per** [microsoft/winget-pkgs#13983]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   Microsoft.OpenJDK.11
PackageVersion:      11.0.11.9
PackageLocale:       en-US
Publisher:           Microsoft
PackageName:         Microsoft OpenJDK 11
License:            GPL2 with Classpath Exception.
ShortDescription:    The Microsoft Build of OpenJDK is a new no-cost long-term supported distribution and Microsoft's new way to collaborate and contribute to the Java ecosystem.
Installers: 
 - Architecture:     x64
   InstallerType:    msi
   InstallerUrl:     https://aka.ms/download-jdk/microsoft-jdk-11.0.11.9.1-windows-x64.msi
   InstallerSha256:  CFBCD0A8C8E983B0DDD94D49476C25CC0B47F7D2289F3FD554CC0A95E5CFE6DD
ManifestType: singleton
ManifestVersion: 1.0.0
```

Need to remove package PREVIEW from package description as the same binary is release as GA here: https://docs.microsoft.com/en-us/java/openjdk/download
