### ISSUE TITLE
Git prerelease Request

### ISSUE THREAD

**Issue by VVB26W34** [microsoft/winget-pkgs#14085]
# Package Requested

Manifest:

```YAML
PackageIdentifier:   Git.GitPrerelease
PackageVersion:      2.32.0-rc1
PackageLocale:       en-US
Publisher:           The Git Development Community
PackageName:         Git prerelease
License:             GNU General Public License version 2
ShortDescription:    Git for Windows focuses on offering a lightweight, native set of tools that bring the full feature set of the Git SCM to Windows while providing appropriate user interfaces for experienced Git users and novices alike.
Installers: 
 - Architecture:     x64
   InstallerType:    inno
   InstallerUrl:     https://wingit.blob.core.windows.net/files/Git-prerelease-2.32.0-rc1.windows.1-37-gcc58341f46-20210525114532-64-bit.exe
   InstallerSha256:  A338CB4A79CE8A802AE07D284C1A4EC960C7E9F1D1D32149852C734500EBC0B2
 - Architecture:     x86
   InstallerType:    inno
   InstallerUrl:     https://wingit.blob.core.windows.net/files/Git-prerelease-2.32.0-rc1.windows.1-37-gcc58341f46-20210525114532-32-bit.exe
   InstallerSha256:  0D0F7F9370A966416BE7C70EA44B31F073A3BB5CE218D942A209BB077C396FE9
ManifestType: singleton
ManifestVersion: 1.0.0
```
