### ISSUE TITLE
Slack Beta Request

### ISSUE THREAD

**Issue by ghost** [microsoft/winget-pkgs#14106]
# Package Requested

Manifest:

```YAML
PackageIdentifier:   SlackTechnologies.SlackBeta
PackageVersion:      4.17.0-beta1   |   4.17.x/bd899c1
PackageLocale:       en-US
Publisher:           Slack Technologies Inc.
PackageName:         Slack Beta
License:             Proprietary
ShortDescription:    Slack brings the team together, wherever you are.
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://downloads.slack-edge.com/releases/windows/4.17.0-beta1/beta/x64/SlackSetup.exe
   InstallerSha256:  615B8455EE8E408C78D1599D0E5689CD6319050692FF7CB0226351FACCC6493C
ManifestType: singleton
ManifestVersion: 1.0.0
```
