### ISSUE TITLE
Visual Studio 2019 Preview Request

### ISSUE THREAD

**Issue by VVB26W34** [microsoft/winget-pkgs#14100]
# Package Requested

Community Manifest:

```YAML
PackageIdentifier:   Microsoft.VisualStudio.2019.CommunityPreview
PackageVersion:      16.11.31320.298
PackageLocale:       en-US
Publisher:           Microsoft Corporation
PackageName:         Visual Studio Community 2019 Preview
License:             Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription:    Free, fully-featured IDE for students, open-source contributors, and individuals.
Installers: 
 - Architecture:     x86
   InstallerType:    exe
   InstallerUrl:     https://download.visualstudio.microsoft.com/download/pr/e527d47a-814f-44bf-9cf8-2c0d9ed19e47/6630e33cd8f95ecd95072b278170153362915399344dd8a28f1c04d0fe5aa551/vs_Community.exe
   InstallerSha256:  6630E33CD8F95ECD95072B278170153362915399344DD8A28F1C04D0FE5AA551
ManifestType: singleton
ManifestVersion: 1.0.0
```

Professional Manifest:

```YAML
PackageIdentifier:   Microsoft.VisualStudio.2019.ProfessionalPreview
PackageVersion:      16.11.31320.298
PackageLocale:       en-US
Publisher:           Microsoft Corporation
PackageName:         Visual Studio Professional 2019 Preview
License:             Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription:    Fully-featured IDE for small teams. Best if you have a Visual Studio Professional subscription.
Installers: 
 - Architecture:     x86
   InstallerType:    exe
   InstallerUrl:     https://download.visualstudio.microsoft.com/download/pr/e527d47a-814f-44bf-9cf8-2c0d9ed19e47/eed73fbfebef4671a001e70a993bab24954087408afd298b6e345466f9e03652/vs_Professional.exe
   InstallerSha256:  EED73FBFEBEF4671A001E70A993BAB24954087408AFD298B6E345466F9E03652
ManifestType: singleton
ManifestVersion: 1.0.0
```

Enterprise Manifest:

```YAML
PackageIdentifier:   Microsoft.VisualStudio.2019.EnterprisePreview
PackageVersion:      16.11.31320.298
PackageLocale:       en-US
Publisher:           Microsoft Corporation
PackageName:         Visual Studio Enterprise 2019 Preview
License:             Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription:    End-to-end solution for teams of any size. Best if you have a Visual Studio Enterprise subscription.
Installers: 
 - Architecture:     x86
   InstallerType:    exe
   InstallerUrl:     https://download.visualstudio.microsoft.com/download/pr/e527d47a-814f-44bf-9cf8-2c0d9ed19e47/b1feac119b6d8b1705d64da88cbb072dc5d644b9cfe9af901bc1b897d5cb3c66/vs_Enterprise.exe
   InstallerSha256:  B1FEAC119B6D8B1705D64DA88CBB072DC5D644B9CFE9AF901BC1B897D5CB3C66
ManifestType: singleton
ManifestVersion: 1.0.0
```
