### ISSUE TITLE
Azure Data Studio Insiders Request

### ISSUE THREAD

**Issue by ghost** [microsoft/winget-pkgs#14103]
# Package Requested

Manifest:

```YAML
PackageIdentifier:   Microsoft.AzureDataStudio.Insiders
PackageVersion:      1.30.0.b75e688a7e
PackageLocale:       en-US
Publisher:           Microsoft Corporation
PackageName:         Azure Data Studio Insiders
License:             Copyright  Microsoft Corporation
ShortDescription:    Azure Data Studio is a data management tool that enables you to work with SQL Server, Azure SQL DB and SQL DW from Windows, macOS and Linux.
Installers: 
 - Architecture:     x64
   InstallerType:    inno
   InstallerUrl:     https://sqlopsbuilds.azureedge.net/insider/b75e688a7ef4364cf75bf15e3d6f4a2d0447011f/azuredatastudio-windows-setup-1.30.0-insider.exe
   InstallerSha256:  A97062FAEDC42C74C74EFA2E94D1F3DF14F32B3DE149B463EB928BC0198E3489
   Scope: machine
 - Architecture:     x64
   InstallerType:    inno
   InstallerUrl:     https://sqlopsbuilds.azureedge.net/insider/b75e688a7ef4364cf75bf15e3d6f4a2d0447011f/azuredatastudio-windows-user-setup-1.30.0-insider.exe
   InstallerSha256:  A41CDE36D31B5844C462919A74180433E427CD3061C70F2C7C4EE6E2836510B6
   Scope: user
ManifestType: singleton
ManifestVersion: 1.0.0
```
