### ISSUE TITLE
Azure Data Studio User Installer Request

### ISSUE THREAD

**Issue by VVB26W34** [microsoft/winget-pkgs#14104]
# Package Requested

Manifest:

```YAML
PackageIdentifier:   Microsoft.AzureDataStudio
PackageVersion:      1.29.0
PackageLocale:       en-US
Publisher:           Microsoft Corporation
PackageName:         Azure Data Studio
License:             Copyright (C) Microsoft Corporation
ShortDescription:    Azure Data Studio is a data management tool that enables you to work with SQL Server, Azure SQL DB and SQL DW from Windows, macOS and Linux.
Installers: 
 - Architecture:     x64
   InstallerType:    inno
   InstallerUrl:     https://sqlopsbuilds.azureedge.net/stable/0f5cfdc2c8c2433028842e16dc5ac1a65da24292/azuredatastudio-windows-user-setup-1.29.0.exe
   InstallerSha256:  804010B465E628772DE5EE197C7D829FACB8A83A58A6533AC08A0ADCB36E1516
   Scope:            user
ManifestType: singleton
ManifestVersion: 1.0.0
```
