### ISSUE TITLE
Update UniversityofLjubljana.Orange to 3.28.0

### ISSUE THREAD

**Issue by dinhanhx** [microsoft/winget-pkgs#14179]
# Package Requested

[Orange 3.28.0 Github release](https://github.com/biolab/orange3/releases/tag/3.28.0)

[Orange 3.28 Installer](https://orangedatamining.com/download/#windows)

Manifest: [UniversityofLjubljana/Orange](https://github.com/microsoft/winget-pkgs/tree/master/manifests/u/UniversityofLjubljana/Orange)

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier: UniversityofLjubljana.Orange  # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion: 3.28.0     # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale: en-US      # meta-data locale (example: "en-US")
Publisher: University of Ljubljana          # publisher name (example: "Microsoft Corporation")
PackageName: Orange       # package name (example: "Windows Terminal")
License: GNU General Public License            # package license (example: "MIT")
ShortDescription: Open source machine learning and data visualization.   # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
