### ISSUE TITLE
[Package Issue]: Microsoft.ServiceFabricSDK - version changes after installation

### ISSUE THREAD

**Issue by cthlo** [microsoft/winget-pkgs#142677]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After installing `Microsoft.ServiceFabricSDK` version `7.0.1949`, the version shown by `winget list` is `7.0.1949.9590`.

Not exactly sure if it's a package issue or an issue with WinGet.

May be related:
When I `winget configure` with the following resource, it always thinks the package is not installed (even after I manually `winget install`):
```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Service Fabric SDK
        allowPrerelease: true
      settings:
        id: Microsoft.ServiceFabricSDK
        source: winget
        version: "7.0.1949"
        installMode: Default
  configurationVersion: "0.2.0"
```

### Steps to reproduce

```powershell
winget install -e --id Microsoft.ServiceFabricSDK --version 7.0.1949 --accept-package-agreements
```

### Actual behavior

```powershell
> winget list -e --id Microsoft.ServiceFabricSDK
Name                               Id                         Version       Source
-----------------------------------------------------------------------------------
Microsoft Azure Service Fabric SDK Microsoft.ServiceFabricSDK 7.0.1949.9590 winget
```

### Expected behavior

The version should be `7.0.1949`.

### Environment

```raw
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0
```
