### ISSUE TITLE
chromedriver request

### ISSUE THREAD

**Issue by kneelesh48** [microsoft/winget-pkgs#14688]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   chromedriver
PackageVersion:      91.0.4472.19
Publisher:           Google
PackageName:         chromedriver
Installers: 
 - Architecture:     x86
   InstallerType:    exe
   InstallerUrl:     https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_win32.zip
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
