### ISSUE TITLE
[Package Issue]: TheDocumentFoundation.LibreOffice.HelpPack

### ISSUE THREAD

**Issue by exoosh** [microsoft/winget-pkgs#149794]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

PR #148486 introduces the the **Taiwanese (Traditional) Chinese** variant of the help pack for architecture **x64**, whereas **x86** remains as en-US:

```
Installers:
- Architecture: x86
  InstallerUrl: https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.2.2/win/x86/LibreOffice_24.2.2.2_Win_x86_helppack_en-US.msi
  InstallerSha256: 397DBBB167681C6AFAD0C33E7869C779D3A152A2AE41CEEEA081864E4092DCF1
  ProductCode: '{DD10966F-8F0A-4F19-BF1D-5CB05C669021}'
  AppsAndFeaturesEntries:
  - DisplayName: LibreOffice 24.2 Help Pack (English (United States))
    UpgradeCode: '{40C2DB8E-E9D6-4451-BE31-DAD1343EC3DF}'
- Architecture: x64
  InstallerUrl: https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.2.2/win/x86_64/LibreOffice_24.2.2.2_Win_x86-64_helppack_zh-TW.msi
  InstallerSha256: ED0D7EF52D0DDDB826863FD6050E3C7D0DA275EC85F48C2F866DAAAC908D9A53
  ProductCode: '{28E98B40-BA56-4366-99AD-DDB6216C6433}'
  AppsAndFeaturesEntries:
  - DisplayName: LibreOffice 24.2 Help Pack (Chinese (traditional))
    UpgradeCode: '{6800BE26-76E9-4280-A174-5A952A18E643}'
```

See the second `InstallerUrl:` key: LibreOffice_24.2.2.2_Win_x86-64_helppack_**zh-TW**.msi

I think much like with the release candidate topic, there should be separate IDs for separate languages for the help packs.

In this particular case I suspect that the fact that the respective contributors are using their browser contributes to getting the localized help pack URLs.

### Steps to reproduce

Simply attempt to upgrade and if you are on x64 or install if it hadn't been installed before.

### Actual behavior

You will get the Chinese help pack installed.

### Expected behavior

I expected the US-English help pack, since the `winget upgrade` output showed `(English (United States))` in the Name column.

### Environment

```raw
>winget --info
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4291
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Enabled
```
