### ISSUE TITLE
[Package Issue]: KRTirtho.Spotube - Which version suffix "+N" is suitable for this package?

### ISSUE THREAD

**Issue by kachick** [microsoft/winget-pkgs#149800]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Multiple installed packages found.

### Brief description of your issue

KRTirtho.Spotube v3.6.0 actually has 2 manifests `3.6.0` and `3.6.0+30`

https://github.com/microsoft/winget-pkgs/blob/a2234ff5cd6a56c5f6eeeb821d8ff6fa07473dfb/manifests/k/KRTirtho/Spotube/3.6.0/KRTirtho.Spotube.installer.yaml#L5
https://github.com/microsoft/winget-pkgs/blob/a2234ff5cd6a56c5f6eeeb821d8ff6fa07473dfb/manifests/k/KRTirtho/Spotube/3.6.0%2B30/KRTirtho.Spotube.installer.yaml#L5

Adding suffix has been started since https://github.com/microsoft/winget-pkgs/pull/141793, but KRTirtho.Spotube official PR is still in no suffix.

https://github.com/microsoft/winget-pkgs/pull/149312
https://github.com/microsoft/winget-pkgs/pull/149329

@KRTirtho @hlqviet Which is desirable way?

### Steps to reproduce

`winget install --exact --id KRTirtho.Spotube`

(Adding `--version 3.6.0` can avoid this problem)

### Actual behavior

Found and install `Spotube [KRTirtho.Spotube] version 3.6.0+30`

### Expected behavior

Found and install `Spotube [KRTirtho.Spotube] version 3.6.0`

### Environment

```raw
> winget --info
v1.7.10861 の Windows パッケージ マネージャー
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
システム アーキテクチャ: X64
パッケージ: Microsoft.DesktopAppInstaller v1.22.10861.0
```

**Comment by KRTirtho** [comment]
@kachick both are correct but someone else is also submitting updates for package. All versions published without +N are authentic and published by me.

**Comment by kachick** [comment]
Thank you for your reply!

@hlqviet If we actually need the suffix, adding the logics in https://github.com/KRTirtho/spotube/blob/cb95663412fcc9a829c5657e0160132f13fb0649/.github/workflows/spotube-publish-binary.yml#L78-L89 maybe good?

**Comment by KRTirtho** [comment]
Thanks for noticing the issue. 
Also, I'll request the maintainers to not accept any PRs from other developers for Spotube except me if possible. I always try to publish it on WinGet with every release officially.

@hlqviet's PRs seems to be a non-malicious so I thanks for his contribution. But just like @kachick asked, please create a PR in the main repo to make a change.

**Comment by hlqviet** [comment]
> Thanks for noticing the issue. Also, I'll request the maintainers to not accept any PRs from other developers for Spotube except me if possible. I always try to publish it on WinGet with every release officially.
> 
> @hlqviet's PRs seems to be a non-malicious so I thanks for his contribution. But just like @kachick asked, please create a PR in the main repo to make a change.

Oh I wasn't aware that you started releasing to winget yourself.

The problem here is that DisplayVersion, which winget uses to check version, is different from the release version. I've just found out that this can be handled by using `AppsAndFeaturesEntries` as follows:
```yml
# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: KRTirtho.Spotube
PackageVersion: 3.6.0
Platform:
- Windows.Desktop
InstallerType: inno
ReleaseDate: 2024-04-15
AppsAndFeaturesEntries:
- DisplayVersion: 3.6.0+30
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/KRTirtho/spotube/releases/download/v3.6.0/Spotube-windows-x86_64-setup.exe
  InstallerSha256: 9047ACDFC2A5D172780ACDBF0A52BF9BC4FC88DEAB0CDEF08ADA7B83D5871508
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/KRTirtho/spotube/releases/download/v3.6.0/Spotube-windows-x86_64-setup.exe
  InstallerSha256: 9047ACDFC2A5D172780ACDBF0A52BF9BC4FC88DEAB0CDEF08ADA7B83D5871508
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0

```
