### ISSUE TITLE
Project64 Request

### ISSUE THREAD

**Issue by Ayfri** [microsoft/winget-pkgs#15018]
# Package Requested

Manifest: 

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   Project64
PackageVersion:      3.0.0.5632
PackageLocale:       en-US
Publisher:           Project64
PackageName:         Project 64
License:             GPLv2
ShortDescription:    Project64 is a free and open-source emulator for the Nintendo 64 and Nintendo 64 Disk Drive written in C++ currently for Windows (planned support for other platforms in the future)
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://www.pj64-emu.com/download/project64-3-0-installer
   InstallerSha256:  260942d23a0b3b99f78950e387071391976832c9ecab3c13d48377e20cccc083
ManifestType: singleton
ManifestVersion: 1.0.0
```
