### ISSUE TITLE
MultiMC

### ISSUE THREAD

**Issue by BlueBurgersTDD** [microsoft/winget-pkgs#15177]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier: MultiMC.MultiMC
PackageVersion: 0.6.12-1530
PackageLocale: en-US
Publisher: MultiMC
PackageName: MultiMC
License: https://github.com/MultiMC/MultiMC5/blob/develop/COPYING.md
ShortDescription: Free, open source launcher for Minecraft
Installers: 
 - Architecture: x86
   InstallerType: Zip
   InstallerUrl: https://files.multimc.org/downloads/mmc-stable-win32.zip
   InstallerSha256: 309FFFF7D48C6F9EEB4B424B812E03A5AD11785D912FBBB7CA065AB4CDF07688
ManifestType: singleton
ManifestVersion: 1.0.0
```
