### ISSUE TITLE
Geekbench 5 not found when upgrading with winget

### ISSUE THREAD

**Issue by JackW6809** [microsoft/winget-pkgs#15720]
The issue with the Geekbench 5.4.1 package not giving a correct name. (https://github.com/microsoft/winget-pkgs/pull/13375)

The issue is, is that winget searches for Geekbench 5 so it cannot find a program corresponding to that exact name. So all that needs to be changed is the package identifier and package name.  
![image](https://user-images.githubusercontent.com/53652452/120468663-5cd7ef00-c399-11eb-87ed-215458b2c2b7.png)

Manifest:

```YAML
PackageIdentifier: PrimateLabs.Geekbench5
PackageVersion: 5.4.1
PackageName: Geekbench 5
Publisher: Primate Labs
License: © 2004-2019 Primate Labs Inc.
Moniker: geekbench
Tags:
- benchmark
- geekbench
ShortDescription: Cross-Platform Benchmark
PackageUrl: https://www.geekbench.com/
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.geekbench.com/Geekbench-5.4.1-WindowsSetup.exe
  InstallerSha256: 0eec12ad0cf91a4f9cb28f8e39b82357ed86b501ce44386ed90a4e7d02e6294a
  InstallerType: exe
  InstallerSwitches:
    Silent: "/S"
    SilentWithProgress: "/S"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
```

**Comment by OfficialEsco** [comment]
Lets see if it works once that PR is Merged, there is however another problem because Geekbench don't show version number in Windows..
![image](https://user-images.githubusercontent.com/15158490/120472540-4c7a4100-c3a6-11eb-80dc-e040f9c9f288.png)
Because of this the Corrent Version will be Unknown and always ask for Upgrade.. (For now)

**Comment by JackW6809** [comment]
Hello @OfficialEsco,

So I just checked to see if that PR fixed the issue and unfortunately it does not. It still cannot find anything for Geekbench 5. I think it needs to be specifically named "Geekbench 5" rather than just "Geekbench" like previously suggested. Due to the way PrimateLabs like to name Geekbench Products.

Kind regards,
Jack.

**Comment by OfficialEsco** [comment]
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget show geekbench
Found Geekbench [PrimateLabs.Geekbench]
Version: 5.4.1
Publisher: Primate Labs
Moniker: geekbench
Description: Cross-Platform Benchmark
Homepage: https://www.geekbench.com/
License: © 2004-2019 Primate Labs Inc.
Installer:
  Type: Exe
  Download Url: https://cdn.geekbench.com/Geekbench-5.4.1-WindowsSetup.exe
  SHA256: 0eec12ad0cf91a4f9cb28f8e39b82357ed86b501ce44386ed90a4e7d02e6294a
```
Once `Publisher` turns into `Primate Labs Inc.` it should work, gotta give the system some time to update 😄 
If it still dosn't work just reopen the case.
