### ISSUE TITLE
Macrium Reflect Free Request

### ISSUE THREAD

**Issue by FunctionDJ** [microsoft/winget-pkgs#15850]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier: Macrium.ReflectFree
PackageVersion: 7.3.5925
PackageLocale: en-US # i speak german, so de-DE, but i think most people would benefit from the english version first
Publisher: Paramount Software UK Limited 
PackageName: ReflectFree
License: # i don't know, it's commercial software / not FOSS
ShortDescription: Free backup, disk imaging and cloning solution for commercial and personal use.
Installers: 
 - Architecture: x64
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
