### ISSUE TITLE
ESETSecurity

### ISSUE THREAD

**Issue by mddtest** [microsoft/winget-pkgs#15957]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

I am having trouble creating a manifest for this one as it requires user intervention and the silent switch does not seem to be working.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   ESET.ESETSecurity
PackageVersion:     10.18.44.0
PackageLocale:       en-US
Publisher:                ESET
PackageName:         ESETSecurity
License:             © 2008-2021 ESET Canada Inc
ShortDescription:    # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     X86
   InstallerType:    EXE
   InstallerUrl:     https://download.eset.com/com/eset/tools/installers/live_essp/latest/eset_smart_security_premium_live_installer.exe
   InstallerSha256:  83C4C68C114FAAC39C2F40941CB30F0E27966DF247945EE6BC9062A0309ED446
ManifestType: singleton
ManifestVersion: 1.0.0
```
