### ISSUE TITLE
Package Request: AusweisApp2

### ISSUE THREAD

**Issue by max-stockhausen** [microsoft/winget-pkgs#16024]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier: governikus.ausweisapp2 # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion: 1.22.1 # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale: de-DE # meta-data locale (example: "en-US")
Publisher: Governikus GmbH & Co. KG # publisher name (example: "Microsoft Corporation")
PackageName: AusweisApp2 # package name (example: "Windows Terminal")
License: EUPL v1.2 # package license (example: "MIT")
ShortDescription: Offizieller eID-Client des Bundes # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl: https://www.ausweisapp.bund.de/fileadmin/user_upload/Software/1.22.2/AusweisApp2-1.22.2.msi # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
