### ISSUE TITLE
JetBrains MPS 2020.3.3 (203.7717.1351)

### ISSUE THREAD

**Issue by abdonmorales** [microsoft/winget-pkgs#16108]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier: JetBrains.MPS
PackageVersion:    203.7717.1351
PackageLocale:     en-US
Publisher:           JetBrains
PackageName:         JetBrains Meta Programming System 2020.3.3
License:             Copyright © JetBrains s.r.o
ShortDescription:  Use the MPS platform to create your own domain-specific language that speaks to your business needs.
Installers: 
 - Architecture:     x64
   InstallerType:   exe
   InstallerUrl:    https://download.jetbrains.com/mps/2020.3/MPS-2020.3.3.exe
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
