### ISSUE TITLE
JetBrains RubyMine 2021.1.2 - 211.7442.41

### ISSUE THREAD

**Issue by abdonmorales** [microsoft/winget-pkgs#16251]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   JetBrains.RubyMine
PackageVersion:      211.7442.41
PackageLocale:       en-US
Publisher:           JetBrains
PackageName:        RubyMine 2021.1.2
License:             Copyright © JetBrains s.r.o.
ShortDescription:    The Ruby and Rails IDE with first-class support for Ruby and Rails, JavaScript and CoffeeScript, ERB and HAML, CSS, Sass and Less, and more.
Installers: 
 - Architecture:    x64
   InstallerType:   exe
   InstallerUrl:     https://download.jetbrains.com/ruby/RubyMine-2021.1.2.exe
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
