### ISSUE TITLE
How to add installer command line arguments?

### ISSUE THREAD

**Issue by DestroyerXyz** [microsoft/winget-pkgs#16250]

**Comment by iDolmatov** [comment]
See https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1
When you create the manifest file, you are prompted for switches that are used to start the installation.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json

```
InstallerSwitches:
  Silent: 
  SilentWithProgress: 
  Interactive: 
  InstallLocation: 
  Log: 
  Upgrade: 
  Custom: 
```
