### ISSUE TITLE
Package Requested: Celestia

### ISSUE THREAD

**Issue by mveril** [microsoft/winget-pkgs#16566]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   Celestia.Celestia
PackageVersion:      1.6.2.2
PackageLocale:       en-US
Publisher:           Celestia Development Team
PackageName:         Celestia
Homepage:            https://celestia.space
License:             GPL-2.0
License Url:         https://github.com/CelestiaProject/Celestia/blob/master/COPYING
ShortDescription:    Real-time 3D visualization of space. The free space simulation that lets you explore our universe in three dimensions.
Installers: 
 - Architecture:     x64
   InstallerType:    Inno
   InstallerUrl:     https://github.com/CelestiaProject/Celestia/releases/download/1.6.2.2/celestia-1.6.2.2-win.exe
   InstallerSha256:  e4773efa942a145300a26dce2f7d66ad9e2f2785d55a3bef2ffd6060d2573564
Installers: 
 - Architecture:     x86
   InstallerType:    Inno
   InstallerUrl:     https://github.com/CelestiaProject/Celestia/releases/download/1.6.2.2/celestia-1.6.2.2-win.exe
   InstallerSha256:  e4773efa942a145300a26dce2f7d66ad9e2f2785d55a3bef2ffd6060d2573564
ManifestType: singleton
ManifestVersion: 1.0.0
```
