### ISSUE TITLE
Package Request: Nerdfonts

### ISSUE THREAD

**Issue by houstdav000** [microsoft/winget-pkgs#17547]
# Nerd Fonts

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

```YAML
PackageIdentifier:   NerdFonts.NerdFonts # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:   2.1.0   # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:   en-US    # meta-data locale (example: "en-US")
Publisher:     N/A?      # publisher name (example: "Microsoft Corporation")
PackageName:   Nerd Fonts      # package name (example: "Windows Terminal")
License:      MIT       # package license (example: "MIT")
ShortDescription:  Fancy Terminal Fonts   # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:  N/A   # installer architecture (example: "x64")
   InstallerType:  None  # installer type (example: "msix")
   InstallerUrl:   https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip  # installer URL (should be https://)
   InstallerSha256: 92B50960305C580FC90BB3BD5456E26EDC9B321907DFA2578066A9B38E2A94E0 # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```

This may be complicated. Nerd Fonts are great for their support of ligatures and many different glyphs, and are widely used for making your terminal fancier. The problem is that instead of providing a single downloader, they break it up into separate zip files for each font, with sets of Windows compatible `ttf`s and `otf`s and non-compatible ones within the zip files.

As such, while writing a font installer might not be hard, this brings up whether to provide this as one large installer as Chocolatey does, or provide individual fonts, or if winget should provide the ability to install fonts at all.
