### ISSUE TITLE
Package Request: wezterm

### ISSUE THREAD

**Issue by timescam** [microsoft/winget-pkgs#17671]
# Package Request: wezterm

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   wez.wezterm # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      20210502-154244-3f7122cb # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           wez # publisher name (example: "Microsoft Corporation")
PackageName:         wezterm # package name (example: "Windows Terminal")
License:             MIT # package license (example: "MIT")
ShortDescription:    A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     x64 # installer architecture (example: "x64")
   InstallerType:    exe # installer type (example: "msix")
   InstallerUrl:     https://github.com/wez/wezterm/releases/download/20210502-154244-3f7122cb/WezTerm-20210502-154244-3f7122cb-setup.exe # installer URL (should be https://)
   InstallerSha256:  e4b44ceee5ed81ae64800fedec349dea4688932ef906d509fb14e3388e0b7c58 # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
