### ISSUE TITLE
Package Request: WPS Office

### ISSUE THREAD

**Issue by Trance-Paradox** [microsoft/winget-pkgs#17842]
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   # wps.office
PackageVersion:      # 11.2.0.10152
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           # wps
PackageName:         # WPS Office
License:             # The FreeType Project LICENSE
ShortDescription:    # Office Tools Along WIth PDF Reader
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # "exe"
   InstallerUrl:     # https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/11.2.0.10152/WPSOffice_11.2.0.10152.exe
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
