### ISSUE TITLE
Package: PyEnv

### ISSUE THREAD

**Issue by XavierGeerinck** [microsoft/winget-pkgs#17988]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:  PyEnv.PyEnv # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:     2.0.1.0 # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:      en-US # meta-data locale (example: "en-US")
Publisher:          PyEnv # publisher name (example: "Microsoft Corporation")
PackageName:        PyEnv   # package name (example: "Windows Terminal")
License:            MIT # package license (example: "MIT")
ShortDescription:   Simple Python version management # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     / # installer architecture (example: "x64")
   InstallerType:    Source Code + Path variable # installer type (example: "msix")
   InstallerUrl:     https://github.com/pyenv/pyenv/releases/tag/v2.0.1 # installer URL (should be https://)
   InstallerSha256:  /# SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```

Note: This was started but never finished? https://github.com/pyenv-win/pyenv-win/issues/134
