### ISSUE TITLE
Spatie Ray

### ISSUE THREAD

**Issue by Morgy93** [microsoft/winget-pkgs#18093]
# Package Requested

- [X] I would like someone else to build the manifest. (Either, or:)
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
Id: Spatie.Ray
Publisher: Spatie
Name: Ray
Version: 1.14.7
License: Copyright (c) Spatie bvba info@spatie.be
InstallerType: EXE
LicenseUrl: https://github.com/spatie/ray/blob/main/LICENSE.md
AppMoniker: ray
Tags: ray
Description: Debug with Ray to fix problems faster
Homepage: https://myray.app/
Installers:
  - Arch: x64
    InstallerType: EXE
    Url: https://spatie.be/products/ray/download/windows/latest
    Sha256: 23B292F7ECE0282711F028D44FD82354974D0C3345EB836A163AF410D3D7BD1B
    Language: en-US
```

I guess the main issue will be the download url which points to the latest version. Could not figure out how to get a specific version.

*Edit*: Asked https://github.com/spatie/ray/discussions/477 for help as well.
