### ISSUE TITLE
[Update Request]: Update IrfanSkiljan.IrfanView to 4.70

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/winget-pkgs#181559]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IrfanSkiljan.IrfanView

### Package Version

4.70

### Please describe the changes you would like to see

New version 4.70:

> **(Release date: 2024-10-11)**
> 
> New option: Keep existing alpha/transparency color (Properties->Viewing)
> Show checkerboard image; Alpha/Color also used for saving
> New option in Increase Color Depth dialog: 32 BPP (with alpha layer)
> New option in Replace Color dialog: Set transparent color (if 32 BPP image)
> New Image menu: Edit or Set alpha/transparency color>
> New option: Show Browse buttons in main window (Properties->Browsing)
> Fine Rotation option can work on selections
> New in OCR PlugIn: read QR or Barcode (thanks to ZXing guys)
> New slideshow hotkey: SHIFT + "," (comma): Toggle random and automatic time
> New Print dialog option: Reverse pages (for multipage images, page ranges)
> Support for EXIF data in WEBP files (EXIF dialog)
> Command line: "/effect" can be combined with "/slideshow", like:
> i_view64.exe /slideshow=c:\mypics.txt /effect=(30,0,0)
> Loading issues in several PlugIns fixed (thanks to Trend Micro)
> (CADImage, Formats, CamRAW, DjVu, JPM, ECW, WSQ)
> SVG PlugIn loading bugs fixed (thanks to nerty_nerty)
> EXR PlugIn loading bugs fixed (thanks to leeho and Who4mI)
> Several PlugIns are changed/updated

**Download:**
https://www.irfanview.com/main_download_engl.htm ( I have no idea which hoster is best for winget)

**Comment by Dragon1573** [comment]
@MagicAndre1981 - In the previous manifest `v4.67`, it uses mirror from **TECHSPOT**.

```yaml
# Created with YamlCreate.ps1 v2.4.1 Dumplings Mod $debug=QUSU.CRLF.7-4-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: IrfanSkiljan.IrfanView
PackageVersion: "4.67"
# Contents folded ...
ReleaseDate: 2024-04-05
Installers:
- Architecture: x86
  InstallerUrl: https://files02.tchspt.com/down/iview467_setup.exe
  InstallerSha256: 5AED8CE9F23EB8A1E11307B641186909AA9A4F41680350DB524EA975BD585CB6
  ProductCode: IrfanView
- Architecture: x64
  InstallerUrl: https://files02.tchspt.com/down/iview467_x64_setup.exe
  InstallerSha256: 15306B139AE4713B88095C4F8ECBD3FF7655D77D3D519FD86572ACE7EA836520
  ProductCode: IrfanView64
ManifestType: installer
ManifestVersion: 1.6.0
```

**TECHSPOT** doesn't provide latest `v4.70` installer. Could you please provide another mirror?

### Recommended (fastest) mirrors

|                                     Mirrors                                      |                             Notes                             |
|:--------------------------------------------------------------------------------:|:-------------------------------------------------------------:|
|              [**FOSSHUB**](https://www.fosshub.com/IrfanView.html)               |               Dynamic generated, encrypted URL                |
|        [**Heise**](https://www.heise.de/software/download/irfanview/1965)        |         `v4.70` not available, `v4.67` is the latest          |
|        [**Fileforum**](https://fileforum.betanews.com/detail/967963863/1)        |         `v4.70` not available, `v4.67` is the latest          |
| [**CNET**](https://download.cnet.com/IrfanView-64-bit/3000-2192_4-76444710.html) |         `v4.70` not available, `v4.62` is the latest          |
|        [**programosy**](https://www.programosy.pl/program,irfanview.html)        | Unsafe installer, blocked by _Microsoft Defender SmartScreen_ |

### Other mirrors

|                                 Mirrors                                  |                    Notes                     |
|:------------------------------------------------------------------------:|:--------------------------------------------:|
|   [**SourceForge**](https://sourceforge.net/projects/irfanview/files/)   | `v4.70` not available, `v4.62` is the latest |
| [**Official site**](https://www.irfanview.info/files/iview470_setup.exe) |        Manual "second click" required        |
