### ISSUE TITLE
Package Request: Rainmeter

### ISSUE THREAD

**Issue by Squaddel** [microsoft/winget-pkgs#18208]
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   # Rainmeter.Rainmeter
PackageVersion:      # 4.3.1.3321
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           # Rainmeter
PackageName:         # Rainmeter
License:             # GNU GPL v2
ShortDescription:    # desktop customization tool
Installers: 
 - Architecture:     # Neutral
   InstallerType:    # EXE
   InstallerUrl:     # https://github.com/rainmeter/rainmeter/releases/download/v4.3.0.3321/Rainmeter-4.3.1.exe
   InstallerSha256:  # EB8F0390F4919C5A2A16B0FF9D5C181DED835ACBEC12E60984BC9BBC3A1F2EF9
ManifestType: singleton
ManifestVersion: 1.0.0
```
