### ISSUE TITLE
[Package Request]:  Questions around onboarding a new package : Microsoft Authentication CLI

### ISSUE THREAD

**Issue by keyuxuan** [microsoft/winget-pkgs#183643]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/AzureAD/microsoft-authentication-cli/releases/tag/0.8.6
Publisher: Microsoft
Package Name: microsoft-authentication-cli
Description: AzureAuth is a CLI wrapper for performing AAD Authentication. It makes use of [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) for authentication and caching.
Package Version: 0.8.6
Installer Url: https://github.com/AzureAD/microsoft-authentication-cli/releases/download/0.8.6/azureauth-0.8.6-win10-x64.zip

i installed winget-cli version `v1.9.2507`  on my machine and I have followed this package to create the manifests using `wingetcreate new` command. Now i have three manifest files and the validation and installation are both successful. 

```
Version manifest preview:
# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Microsoft.microsoft-authentication-cli
PackageVersion: 0.8.6
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
```

```
Installer manifest preview:
# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.microsoft-authentication-cli
PackageVersion: 0.8.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: azureauth.exe
Installers:
- InstallerUrl: https://github.com/AzureAD/microsoft-authentication-cli/releases/download/0.8.6/azureauth-0.8.6-win10-x64.zip
  Architecture: x64
  InstallerSha256: 6E1AB3F38B2A3BA5096FE818B27B1C850DF43D947DF80AA5935425BD978CA54E
ManifestType: installer
ManifestVersion: 1.6.0
```

```
Default locale manifest preview:
# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Microsoft.microsoft-authentication-cli
PackageVersion: 0.8.6
PackageLocale: en-US
Publisher: Microsoft
PackageName: microsoft-authentication-cli
License: MIT License
ShortDescription: AzureAuth is a CLI wrapper for performing AAD Authentication. It makes use of MSAL for authentication and caching.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
```

However, when i tested the command `azureauh --version`, i ran into this issue `The application to execute does not exist: 'C:\Users\keyuxuan\AppData\Local\Microsoft\WinGet\Links\azureauth.dll'.`. 

 Does anyone know why this happens even tho installation was successful and how to fix this?

![Image](https://github.com/user-attachments/assets/e7b6c3cb-c88f-4c8d-b915-43617595d62c)

![Image](https://github.com/user-attachments/assets/39466693-00a3-4d2c-8eac-a635b8002f06)
