### ISSUE TITLE
Citrix Submission Request

### ISSUE THREAD

**Issue by aarongalipeau-excedeo** [microsoft/winget-pkgs#18429]
# Package Requested

- [x] I have performed a search and couldn't find this package.
Citrix Workspace
Manifest:

```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      Version: 21.6.0.47 (2106)
PackageLocale:       en-US
Publisher:                Citrix
PackageName:        CitrixWorkspaceApp
License:                   NLR
ShortDescription:    Citrix Workspace App WinGet Package
Installers: 
 - Architecture:        x64
   InstallerType:        exe
   InstallerUrl:           https://www.citrix.com/downloads/workspace-app/windows/workspace-app-for-windows-latest.html#ctx-dl-eula
   InstallerSha256:    9a6d19422f5e666ffc0029766f96397838e7f740d5823582feec8604dae50970
ManifestType: singleton
ManifestVersion: 1.0.0
```
