### ISSUE TITLE
Maxima manifest does not contain the x64 version and is outdated

### ISSUE THREAD

**Issue by mveril** [microsoft/winget-pkgs#18844]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [x] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   MaximaTeam.Maxima
PackageVersion:      5.45.1
PackageLocale:        en-US
Publisher:           Maxima Team
PackageName:         Maxima 
License:             GNU General Public License (GPL)
ShortDescription:    A Computer Algebra System
Installers: 
 - Architecture:     x86
   InstallerType:    nullsoft
   InstallerUrl:     https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.45.1-Windows/maxima-5.45.1-win32.exe/download
   InstallerSha256:  b2ab4d399ec7ecde4ff6bfb0f64f51bfdf52305733a834fe3d5b591922330714Installers: 
 - Architecture:     x64
   InstallerType:    nullsoft
   InstallerUrl:     https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.45.1-Windows/maxima-5.45.1-win64.exe/download
   InstallerSha256:  245611bdc5c43267ac444a377d40663962265e94db0c59c4831d84d05ddfeadc
ManifestType: singleton
ManifestVersion: 1.0.0
```
