### ISSUE TITLE
Nvidia Game Ready Drivers

### ISSUE THREAD

**Issue by mariobrostech** [microsoft/winget-pkgs#18879]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifests:

Desktop:
```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      1.0.11.0
PackageLocale:       International
Publisher:           Nvidia Corporation
PackageName:         Nvidia Game Ready Driver
License:             Proprietary
ShortDescription:    Game-ready graphics driver for Nvidia GeForce GPUs
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://us.download.nvidia.com/Windows/471.11/471.11-desktop-win10-64bit-international-dch-whql.exe
   InstallerSha256:  c81810bd968ba6efe0b1052301c242d081dfd843d91fc9e2e46cbce3fc527719
ManifestType: singleton
ManifestVersion: 1.0.0
```

Laptop:
```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      1.0.11.0
PackageLocale:       International
Publisher:           Nvidia Corporation
PackageName:         Nvidia Game Ready Driver
License:             Proprietary
ShortDescription:    Game-ready graphics driver for Nvidia GeForce GPUs
Installers: 
 - Architecture:     x64
   InstallerType:    exe
   InstallerUrl:     https://us.download.nvidia.com/Windows/471.11/471.11-notebook-win10-64bit-international-dch-whql.exe
   InstallerSha256:  c81810bd968ba6efe0b1052301c242d081dfd843d91fc9e2e46cbce3fc527719
ManifestType: singleton
ManifestVersion: 1.0.0
```

Notes:
- The installer hashes seem to be equal despite them having different installer names and URLs. Would it be necessary to differentiate between the two if the packages are exactly the same?
- How should I determine the package identifier for this application?
- I haven't tested for a silent install option, nor do I know how to. Could someone please help me with this?
- If you're thinking about closing this issue since there is already a winget package available for Nvidia GeForce Experience, please don't! This are not the same package, and Nvidia GeForce Experience necessitates the installation of the entire Nvidia software stack and requires you to have an account with them in order to install driver updates.

Thanks in advance!
