### ISSUE TITLE
[Update Request]: astral-sh.uv v0.5.5

### ISSUE THREAD

**Issue by FishAlchemist** [microsoft/winget-pkgs#194715]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

astral-sh.uv

### Package Version

0.5.5

### Please describe the changes you would like to see

Releases 0.5.5 https://github.com/astral-sh/uv/releases/tag/0.5.5

### A suggested description for the license: You don't have to, but it would be great if you could use this.
https://github.com/microsoft/winget-pkgs/blob/1cb6fe2e5f2beb371fc2b3f7d538890c82ed61e9/manifests/a/astral-sh/uv/0.5.4/astral-sh.uv.locale.en-US.yaml#L13-L16

Suggestions for version 0.5.5
 https://github.com/astral-sh/uv/blob/0.5.5/README.md#license 
```yaml
 License: Either the Apache-2.0 License, or the MIT License 
 LicenseUrl: https://github.com/astral-sh/uv/blob/0.5.5/README.md#license 
 Copyright: Copyright (c) 2024 Astral Software Inc. 
 CopyrightUrl: https://github.com/astral-sh/uv/blob/0.5.5/README.md#license 
````
