### ISSUE TITLE
Add Prowise Presenter 1.0.0

### ISSUE THREAD

**Issue by JonasTheGamer** [microsoft/winget-pkgs#19503]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier: Prowise.ProwisePresenter # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion: 1.0.0  # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale: nl-be      # meta-data locale (example: "en-US")
Publisher: Prowise B.V.           # publisher name (example: "Microsoft Corporation")
PackageName: Prowise Presenter        # package name (example: "Windows Terminal")
License:             # package license (example: "MIT")
ShortDescription: The presenter software from Prowise.  # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture: x64    # installer architecture (example: "x64")
   InstallerType: exe   # installer type (example: "msix")
   InstallerUrl: https://presenter0prowise.blob.core.windows.net/production/presenter-electron/Prowise%20Presenter%20Setup%201.0.0.exe    # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
