### ISSUE TITLE
Add Fundels 3.0.10.

### ISSUE THREAD

**Issue by JonasTheGamer** [microsoft/winget-pkgs#19504]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier: Cartamundi.Fundels   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion: 3.0.10     # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale: nl-be      # meta-data locale (example: "en-US")
Publisher: Cartamundi           # publisher name (example: "Microsoft Corporation")
PackageName: Fundels        # package name (example: "Windows Terminal")
License:             # package license (example: "MIT")
ShortDescription: Fundels software for primary school teachers   # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture: x64    # installer architecture (example: "x64")
   InstallerType: exe   # installer type (example: "msix")
   InstallerUrl: https://www.fundels.com/download/fundels_exe    # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```

Thanks in advance!
