### ISSUE TITLE
add Rainmeter

### ISSUE THREAD

**Issue by ahmed-tasaly** [microsoft/winget-pkgs#19581]
# Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   rainmeter.Rainmeter  # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:   4.4   # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:   en-US    # meta-data locale (example: "en-US")
Publisher:   rainmeter        # publisher name (example: "Microsoft Corporation")
PackageName:   Rainmeter-beta      # package name (example: "Windows Terminal")
License:   "GNU GPL v2"     # package license (example: "MIT")
ShortDescription:   " desktop customization tool" # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:   x64  # installer architecture (example: "x64")
   InstallerType:   exe # installer type (example: "msix")
   InstallerUrl:   https://github.com/rainmeter/rainmeter/releases/download/v4.4.0.3493/Rainmeter-4.4-r3493-beta.exe  # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
Thanks in advance
