### ISSUE TITLE
[Package Issue]: Starship.Starship

### ISSUE THREAD

**Issue by 720720** [microsoft/winget-pkgs#196156]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

`winget install --scope machine --exact --id Starship.Starship` creates a portable starship installation in
`C:\Program Files\WinGet\Packages\starship`

### Steps to reproduce

`winget install --scope machine --exact --id Starship.Starship`

### Actual behavior

`winget install --scope machine --exact --id Starship.Starship` downloads
`https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.zip` and installs starship to
`C:\Program Files\WinGet\Packages\starship`

### Expected behavior

`winget install --scope machine --exact --id Starship.Starship` should download
`https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.msi` and install starship to
`C:\Program Files\starship`

### Environment

```raw
Windows Package Manager v1.9.25200
Windows: Windows.Desktop v10.0.22631.4460
Package: Starship.Starship v1.21.1
```

**Comment by Dragon1573** [comment]
```text
11:46:46 D:\...\winget-pkgs  [master ≡] 0ms pwsh> gsudo { winget install --exact --id Starship.Starship }   
已找到 starship [Starship.Starship] 版本 1.21.1
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.msi

11:47:14 D:\...\winget-pkgs  [master ≡] 11.758s 0x0001 pwsh> gsudo { winget install --scope machine --exact --id Starship.Starship }
执行此命令时发生意外错误： 
0x8000ffff : 灾难性故障

11:47:33 D:\...\winget-pkgs  [master ≡] 5.257s pwsh> winget install --scope machine --exact --id Starship.Starship          
打开预定义源失败; 请向 winget 维护人员报告。
执行此命令时发生意外错误： 
0x80070005 : 拒绝访问。

11:49:25 D:\...\winget-pkgs  [master ≡] 0ms pwsh> winget --info
Windows 程序包管理器 v1.9.25200
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.26100.2454
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.24.25200.0

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已启用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已启用
LocalArchiveMalwareScanOverride           已禁用
ProxyCommandLineOptions                   已禁用
DefaultProxy                              已禁用
```

I'm not able to run without `gsudo` elevation or install to machine scope. Unable to reproduce your issue. 😞

**Comment by 720720** [comment]
```
PS E:\> winget install --scope machine --exact --id Starship.Starship
Found starship [Starship.Starship] Version 1.21.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.zip
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "starship"
Path environment variable modified; restart your shell to use the new value.
Successfully installed
```

**Comment by 720720** [comment]
https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/Starship/Starship/1.21.1/Starship.Starship.installer.yaml

```
PackageIdentifier: Starship.Starship
PackageVersion: 1.21.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.msi
  InstallerSha256: 90620DF005C45AC000EF301C980239087E787A74AE92651E7C1B0F2CDC0B5BC6
  ProductCode: '{BBB12985-822B-45F1-9AF3-CF85C368763E}'

```

```
PackageIdentifier: Starship.Starship
PackageVersion: 1.21.1
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x64
  Scope: machine
  InstallerType: wix
  InstallerUrl: https://github.com/starship/starship/releases/download/v1.21.1/starship-x86_64-pc-windows-msvc.msi
  InstallerSha256: 90620DF005C45AC000EF301C980239087E787A74AE92651E7C1B0F2CDC0B5BC6
  ProductCode: '{BBB12985-822B-45F1-9AF3-CF85C368763E}'

```

perhaps a scope definition could fix that problem
