### ISSUE TITLE
Roam Research

### ISSUE THREAD

**Issue by AlJohri** [microsoft/winget-pkgs#19920]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

Useful Links:
- https://roam-electron-deploy.s3.us-east-2.amazonaws.com/latest.yml
- https://roam-electron-deploy.s3.us-east-2.amazonaws.com/latest-mac.yml
- https://roam-electron-deploy.s3.us-east-2.amazonaws.com/latest-linux.yml
- https://roam-electron-deploy.s3.us-east-2.amazonaws.com/Roam+Research+Setup+0.0.13.exe

```YAML
PackageIdentifier: RoamResearch.RoamResearch
PackageVersion: 0.0.13
PackageLocale: en-US
Publisher: Roam Research
PackageName: Roam Research
License:
ShortDescription: A note taking tool for networked thought
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl: https://roam-electron-deploy.s3.us-east-2.amazonaws.com/Roam+Research+Setup+0.0.13.exe
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
