### ISSUE TITLE
Package Naming Correction (RStudio)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [microsoft/winget-pkgs#20217]
# Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           # publisher name (example: "Microsoft Corporation")
PackageName:         # package name (example: "Windows Terminal")
License:             # package license (example: "MIT")
ShortDescription:    # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```

RStudio should be renamed RStudio Desktop because they have two versions, RStudio Desktop and RStudio Server.
Even in RStudio Desktop, they have two editions, RStudio Desktop Open-Source and RStudio Desktop Pro.

Hence, to give a user more detailed information about the package, here is what I think should be correct : 
- RStudio.RStudioDesktop.OpenSource
- RStudio.RStudioDesktop.Pro
- RStudio.RStudioServer.OpenSource
- RStudio.RStudioServer.Workbench

If you agree, I will create a PR otherwise I won't.

Sorry, I had to create the issue under "Issue-Feature" but I forgot earlier.
