### ISSUE TITLE
Stream-Pi Server

### ISSUE THREAD

**Issue by quimodotcom** [microsoft/winget-pkgs#20317]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   Stream_Pi.Server
PackageVersion:      EA+3
PackageLocale:       en-US
Publisher:           Stream-Pi
PackageName:         Stream-Pi Server
License:             GPL-3.0
ShortDescription:    The Early Access Release of Stream-Pi Server (Ver. EA+3)
Installers: 
 - Architecture:     x64
   InstallerType:    msi
   InstallerUrl:     https://github.com/stream-pi/server/releases/download/1.0.0-EA%2B3/stream-pi-server-windows-x64-1.0.0-EA+3-installer.msi
   InstallerSha256:  0c5f6fa3665ca14290f01621746bdb9a599277fdd34e31d69d3ea617f78d6af3
ManifestType: singleton
ManifestVersion: 1.0.0
```
