### ISSUE TITLE
Stream-Pi Client

### ISSUE THREAD

**Issue by quimodotcom** [microsoft/winget-pkgs#20320]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   Stream_Pi.Client
PackageVersion:      EA+3
PackageLocale:       en_US
Publisher:           Stream-Pi
PackageName:         Stream-Pi Client
License:             GPL-3.0
ShortDescription:    The Early Access Release of Stream-Pi Client (Ver. EA+3)
Installers: 
 - Architecture:     x64
   InstallerType:    msi
   InstallerUrl:     https://github.com/stream-pi/client/releases/download/1.0.0-EA%2B3/stream-pi-client-windows-x64-1.0.0-EA+3-installer.msi
   InstallerSha256:  6b36c20fcfad1f85ee9e9eceffde8d90f8f9ff223c9e31f69477fdac835b7624
ManifestType: singleton
ManifestVersion: 1.0.0
```
