### ISSUE TITLE
Package Request: Genshin Impact

### ISSUE THREAD

**Issue by UserFiftyOne** [microsoft/winget-pkgs#20435]
# Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   miHoYo.GenshinImpact # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      2.9.1.0 # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:       en-US# meta-data locale (example: "en-US")
Publisher:           miHoYo Co., Ltd. # publisher name (example: "Microsoft Corporation")
PackageName:         Genshin Impact # package name (example: "Windows Terminal")
License:             # package license (example: "MIT")
ShortDescription:    a free-to-play action role-playing game # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     x64 # installer architecture (example: "x64")
   InstallerType:    exe # installer type (example: "msix")
   InstallerUrl:     https://genshinimpact.mihoyo.com/client_app/launcher/20210609_faac20994b76230c/GenshinImpact_install_mihoyo_20210525204658.exe # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
