### ISSUE TITLE
[Package Issue]: ScooterSoftware.BeyondCompare.5

### ISSUE THREAD

**Issue by 720720** [microsoft/winget-pkgs#207619]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget does not find an applicable installer for the en-US locale.

The reason for this behaviour is probably a missing _InstallerLocale: en-US_ definition.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/ScooterSoftware/BeyondCompare/5/5.0.4.30422/ScooterSoftware.BeyondCompare.5.installer.yaml

```
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://www.scootersoftware.com/files/BCompare-5.0.4.30422.exe
  InstallerSha256: D74892601A50514B5636E27D4BE4D3AC38597F2F6C7C7B6B5B169A48FFA1F341
  InstallerSwitches:
    Custom: /CURRENTUSER
```

```
Installers:
- InstallerLocale: en-US
  Architecture: x86
  Scope: user
  InstallerUrl: https://www.scootersoftware.com/files/BCompare-5.0.4.30422.exe
  InstallerSha256: D74892601A50514B5636E27D4BE4D3AC38597F2F6C7C7B6B5B169A48FFA1F341
  InstallerSwitches:
    Custom: /CURRENTUSER
```

### Steps to reproduce

Windows 11 Pro German

`winget install ScooterSoftware.BeyondCompare.5 --locale en-US`

### Actual behavior

`winget install ScooterSoftware.BeyondCompare.5 --locale en-US`

Es wurde kein anwendbarer Installer gefunden. Weitere Informationen finden Sie in den Protokollen.

### Expected behavior

`winget install ScooterSoftware.BeyondCompare.5 --locale en-US`

Gefunden Beyond Compare 5 [ScooterSoftware.BeyondCompare.5] Version 5.0.4.30422
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Download läuft https://www.scootersoftware.com/files/BCompare-5.0.4.30422.exe
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert

### Environment

```raw
Windows Package Manager v1.9.25200
Windows: Windows.Desktop v10.0.26100.2605
Package: Microsoft.DesktopAppInstaller v1.24.25200.0
```
