### ISSUE TITLE
[New Feature]: Autodesk SFX extraction support

### ISSUE THREAD

**Issue by rovabunw** [microsoft/winget-pkgs#207759]
### Description of the new feature/enhancement

There are numerous Autodesk single file:
https://github.com/microsoft/winget-pkgs/pull/202952

and multiple file setup where two or more setup files need to be downloaded:
https://github.com/microsoft/winget-pkgs/pull/205933

It would be great to support these kind of setups in Winget. However, they need a specific approach to be installed in an unattend/silent way:

1) sfx extraction

First the sfx.exe (e.g. AutoCAD_2022_English_Win_64bit_dlm.sfx.exe) needs to be extracted using:

-suppresslaunch -d

2) run setup.exe

Then in the extracted directory (e.g. ..\AutoCAD_2022_English_Win_64bit_dlm\setup.exe) setup.exe needs to be run using a silent switch e.g. -q

SFX installers can be detected because they are signed by Autodesk* and use a filename which has a specific pattern. 
A byte pattern detection is also an option, searching for e.g. src\bin\Release\AdDLMgrSFX.pdb.

**Comment by Dragon1573** [comment]
I think it would be great supporting configurations like follows:

```yaml
InstallerType: sfx
InstallerSwitches:  # They're for the sfx itself.
  Silent: -suppresslaunch -d
  SilentWithProgress: -suppresslaunch -d
NestedInstallerType: exe
NestedInstallerSwitches:  # They're for the nested install wizard.
  Silent: -q
  SilentWithProgress: -p
```
