### ISSUE TITLE
[Package Request]: git-ecosystem.git-credential-manager

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#217864]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.6.1

```yaml
Publisher: git-ecosystem # (or just Git?)
PackageName: Git Credential Manager
ShortDescription: Secure, cross-platform Git credential storage with authentication to GitHub, Azure Repos, and other popular Git hosting services.
Description: |
  [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) (GCM) is a secure [Git credential helper](https://git-scm.com/docs/gitcredentials) built on [.NET](https://dotnet.microsoft.com/) that runs on Windows, macOS, and Linux. It aims to provide a consistent and secure authentication experience, including multi-factor auth, to every major source control hosting service and platform.
  GCM supports (in alphabetical order) [Azure DevOps](https://azure.microsoft.com/en-us/products/devops), Azure DevOps Server (formerly Team Foundation Server), Bitbucket, GitHub, and GitLab. Compare to Git's [built-in credential helpers](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) (Windows: wincred, macOS: osxkeychain, Linux: gnome-keyring/libsecret), which provide single-factor authentication support for username/password only.
  GCM replaces both the .NET Framework-based [Git Credential Manager for Windows](https://github.com/microsoft/Git-Credential-Manager-for-Windows) and the Java-based [Git Credential Manager for Mac and Linux](https://github.com/microsoft/Git-Credential-Manager-for-Mac-and-Linux).
PackageVersion: 2.6.1
Commands:
- git-credential-manager
Installers: # By komac
  - Architecture: x86
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
    - RelativeFilePath: git-credential-manager.exe
    InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-win-x86-2.6.1.zip
    InstallerSha256: BDDBC4A051FBFA67D70CD2B89D49229FC1A7788F8A9296DA914FB3C42B783D7E
  - InstallerLocale: en-US
    Architecture: x86
    InstallerType: inno
    Scope: machine
    InstallerUrl: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-win-x86-2.6.1.exe
    InstallerSha256: 6C8E66B51D907ECC5C241A9CF0E8B29D8231840A958DFAFBE9F1CBE030EBA7E6
    ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
    AppsAndFeaturesEntries:
    - Publisher: GitHub
      DisplayVersion: 2.6.1.0
      ProductCode: '{fdfae50a-1bc1-4ead-9228-1e1c275e8d12}}_is1'
    ElevationRequirement: elevatesSelf
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\Git Credential Manager'
```
Docs: https://github.com/git-ecosystem/git-credential-manager/tree/release/docs
