### ISSUE TITLE
[Update Request]: DuckStudio.ChineseGit version 3.1

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#218799]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.ChineseGit

### Package Version

3.1

### Please describe the changes you would like to see

Release: https://github.com/DuckDuckStudio/Chinese_git/releases/tag/v3.1
inno setup for any cpu: https://github.com/DuckDuckStudio/Chinese_git/releases/download/v3.1/Chinese_git_Setup_v3.1.exe
zip archive: https://github.com/DuckDuckStudio/Chinese_git/releases/download/v3.1/Chinese_git.zip
```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Git.Git
```
