### ISSUE TITLE
[Package Request]: television

### ISSUE THREAD

**Issue by alexpasmantier** [microsoft/winget-pkgs#221012]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/alexpasmantier/television/releases/download/0.10.3/tv-0.10.3-windows-x86_64.zip
Publisher: Alexandre Pasmantier
Package Name: Television
Description: A fast and versatile fuzzy finder TUI.
Package Version: 0.10.3
Installer Url: https://github.com/alexpasmantier/television/releases/download/0.10.3/tv-0.10.3-windows-x86_64.zip

**Comment by alexpasmantier** [comment]
I was able to produce the following YAML spec using komac but publishing it results in an error.

```yaml
# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Television.Television
PackageVersion: 0.10.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tv.exe
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- tv
ReleaseDate: 2025-01-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/alexpasmantier/television/releases/download/0.10.3/tv-0.10.3-windows-x86_64.zip
  InstallerSha256: 50A862CFBF8DAFE90F52E63FC3350A7CFE32325AC4119FD5B3B72DDA529E8EF6
ManifestType: installer
ManifestVersion: 1.9.0

# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Television.Television
PackageVersion: 0.10.3
PackageLocale: en-US
Publisher: Alexandre Pasmantier
PublisherUrl: https://github.com/alexpasmantier
PublisherSupportUrl: https://github.com/alexpasmantier
Author: Alexandre Pasmantier
PackageName: Television
PackageUrl: https://github.com/alexpasmantier/television
License: MIT
LicenseUrl: https://github.com/alexpasmantier/television/blob/main/LICENSE
ShortDescription: A fast and versatile fuzzy finder TUI.
Description: A fast and versatile fuzzy finder TUI.
Moniker: television
Tags:
- cli
- command-line-tool
- fuzzy
- fuzzy-matching
- fuzzy-search
- rust
- terminal
- tui
ReleaseNotesUrl: https://github.com/alexpasmantier/television/releases
ManifestType: defaultLocale
ManifestVersion: 1.9.0

# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Television.Television
PackageVersion: 0.10.3
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
```
