### ISSUE TITLE
[Package Issue]: ArturoLang.Arturo

### ISSUE THREAD

**Issue by RickBarretto** [microsoft/winget-pkgs#233853]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

I can't install my package locally to upload to the repository.

### Steps to reproduce

Using Powershell's terminal as Administrator:

Right after creating a PR via:

```
PS C:\Users\...> wingetcreate.exe new https://github.com/arturo-lang/arturo/releases/download/v0.9.83/arturo-0.9.83-full-x
86_64-windows.zip
```

```
PS C:\Users\...> winget settings --enable LocalManifestFiles
PS C:\Users\...> winget install --manifest ./manifests/a/ArturoLang/Arturo/0.9.83/ --logs
Encontrado Arturo [ArturoLang.Arturo] Versão 0.9.83
Este aplicativo é licenciado para você pelo proprietário.
A Microsoft não é responsável por, nem concede licenças a pacotes de terceiros.
Hash do instalador verificado com êxito
Extraindo arquivo...
Arquivo extraído com êxito
Iniciando a instalação do pacote...
O alias da linha de comando foi adicionado: "arturo"
Instalado com êxito
```

### Actual behavior

Then I close the terminal and open a new one:

```
PS C:\Users\...> arturo
arturo : O termo 'arturo' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável.
Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ arturo
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (arturo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\rickb> where arturo
```

### Expected behavior

Opening the language's REPL on terminal.

### Environment

```raw
Gerenciador de Pacotes do Windows v1.10.320
Copyright (c) Microsoft Corporation. Todos os direitos reservados.

Windows: Windows.Desktop v10.0.22631.4890
Arquitetura do Sistema: X64
Pacote: Microsoft.DesktopAppInstaller v1.25.320.0

Diretórios Winget
-----------------------------------------------------------------------------------------------------------------------
Registros                                 %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Configurações do Usuário                  %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalSta…
Diretório de Links Portáteis (Usuário)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Diretório de Links Portáteis (Computador) C:\Program Files\WinGet\Links
Raiz do Pacote Portátil (Usuário)         %LOCALAPPDATA%\Microsoft\WinGet\Packages
Raiz do Pacote Portátil                   C:\Program Files\WinGet\Packages
Raiz do Pacote Portátil (x86)             C:\Program Files (x86)\WinGet\Packages
Downloads do Instalador                   %USERPROFILE%\Downloads
Módulos de Configuração                   %LOCALAPPDATA%\Microsoft\WinGet\Configuration\Modules

Links
-------------------------------------------------------------------------------
Política de Privacidade https://aka.ms/winget-privacy
Contrato de Licença     https://aka.ms/winget-license
Avisos de Terceiros     https://aka.ms/winget-3rdPartyNotice
Home page               https://aka.ms/winget
Termos da Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Configuração do Administrador             Estado
------------------------------------------------------
LocalManifestFiles                        Habilitado
BypassCertificatePinningForMicrosoftStore Desabilitado
InstallerHashOverride                     Desabilitado
LocalArchiveMalwareScanOverride           Desabilitado
ProxyCommandLineOptions                   Desabilitado
DefaultProxy                              Desabilitado
```

### Screenshots and Logs

- PR related #233848

No log generated, even with `--logs` enabled.

### Manifest

**ArturoLang.Arturo.yaml**

```
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: ArturoLang.Arturo
PackageVersion: 0.9.83
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0

```

**ArturoLang.Arturo.installer.yaml**

```yml
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ArturoLang.Arturo
PackageVersion: 0.9.83
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: arturo-full-x86_64-windows-latest\arturo.exe
  PortableCommandAlias: arturo
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/arturo-lang/arturo/releases/download/v0.9.83/arturo-0.9.83-full-x86_64-windows.zip
  InstallerSha256: 15E99CD71AF5B12AD2E3EB66BBD15CBED4ACF5126CE43458144D33AC73A6E24C
ManifestType: installer
ManifestVersion: 1.9.0
```

**ArturoLang.Arturo.locale.en-US.yaml**

```
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: ArturoLang.Arturo
PackageVersion: 0.9.83
PackageLocale: en-US
Publisher: ArturoLang
PackageName: Arturo
License: MIT License
ShortDescription: Simple, expressive & portable programming language for efficient scripting.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
```
