### ISSUE TITLE
[Package Issue]: Wakatime.DesktopWakatime

### ISSUE THREAD

**Issue by FlippingBinary** [microsoft/winget-pkgs#234791]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Wakatime installs successfully, but running it fails on new Windows installations.

### Steps to reproduce

1. Install a fresh copy of Windows 11 or open Windows Sandbox and install winget.
2. Install Wakatime with `winget --id Wakatime.DesktopWakatime -e`
3. Attempt to launch Wakatime.

### Actual behavior

Installation completes successfully, but launching the application causes a Javascript error to appear. The error indicates a module could not be found.

### Expected behavior

Application should run properly.

### Environment

```raw
Windows Package Manager v1.10.340
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.3194
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.25.340.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads
Configuration Modules              %LOCALAPPDATA%\Microsoft\WinGet\Configuration\Modules

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

![Image](https://github.com/user-attachments/assets/2e182716-b75a-47bb-b0ee-adaee7b1d81c)

This is similar to an error reported on the app's repository: https://github.com/wakatime/desktop-wakatime/issues/70

A more detailed error appears when running the app in developer mode with `npm run dev` after cloning from its repository:

![Image](https://github.com/user-attachments/assets/04a93e46-0ca9-4e6a-ad0e-20b4498c9ef9)

```
Error: The specified module could not be found.
\\?\C:\Users\WDAGUtilityAccount\Documents\desktop-wakatime\node_modules\@miniben90\x-win-win32-x64-msvc\x-win.win32-x64-msvc.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2559)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\WDAGUtilityAccount\Documents\desktop-wakatime\node_modules\@miniben90\x-win\index.js:72:29)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
```

In this error, I noticed the `-msvc` suffix and thought this might be indicate an undocumented dependency on `Microsoft.VCRedist.2015+`. To test this theory, I installed it manually and tried running the app, which now works. Therefore, I think the dependency should be added to the installer manifest,:

```
manifest.installer.1.9.0.schema.json

PackageIdentifier: Wakatime.DesktopWakatime
PackageVersion: 2.1.2
InstallerLocale: en-US
InstallerType: nullsoft
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/wakatime/desktop-wakatime/releases/download/v2.1.2/wakatime-win32-ia32.exe
  InstallerSha256: 872A54323676D69491AF9A634862762ED92FBB5805BA33B5B41E4B2E523338F1
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  InstallerUrl: https://github.com/wakatime/desktop-wakatime/releases/download/v2.1.2/wakatime-win32-x64.exe
  InstallerSha256: E1B2AA1FB455D9E42707FB6091BDE0D7D1A7ECC382EF427C06FC25EE6E6DF717
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/wakatime/desktop-wakatime/releases/download/v2.1.2/wakatime-win32-arm64.exe
  InstallerSha256: 902BFAA28C14A1FDC01BEAF8FD853FB09CA37EADFB51B88A178B2068DF3D9FED
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2024-12-18
```

I didn't test that manifest, and I'm not very experienced at writing winget manifests, but that illustrates basically what I would suggest changing. This is not a bug that would be noticed by most developers who install the Wakatime desktop app this way because the dependency is so common that they probably already have it installed.

Since @KarbitsCode has been actively maintaining the package, perhaps it would be better if they made the necessary changes at their convenience, but I'm willing to write and test a pull request, if needed.
