### ISSUE TITLE
[Update Request]: Revopoint Revo Scan

### ISSUE THREAD

**Issue by hho** [microsoft/winget-pkgs#234823]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Revopoint.RevoScan

### Package Version

5.5.2.1680

### Please describe the changes you would like to see

There is a new release (5.5.2) available.
Download page: https://www.revopoint3d.com/pages/support-download

```yaml
PackageVersion: 5.5.2.1680
ReleaseDate: 2025-01-07
Installers:
- Architecture: x64
  InstallerUrl: https://download.revopoint3d.com/soft/RevoScan5-5.5.2.1680-windows-x86_64.exe
  InstallerSha256: 17A387514FC26E26A07F4AD487242818A9529AC1CC7928273464951CD3FD38E2
```
