### ISSUE TITLE
[Update Request]: DuckStudio.GitHubView version 2025.03.07.13718228324

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#235623]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.GitHubView

### Package Version

2025.03.07.13718228324

### Please describe the changes you would like to see

Release: https://github.com/DuckDuckStudio/GitHubView/releases/tag/2025.03.07.13718228324
ReleaseNotes:
```markdown
<!-- zh-CN -->
## 新增
- feat(icon): 新图标

## 杂项
- chore(.net): 将框架从 .NET 8 改为 .NET 9

**完整提交记录**: https://github.com/DuckDuckStudio/GitHubView/compare/1.0.3...2025.03.07.13718228324
```

```markdown
<!-- en-US -->
## New
- feat(icon): new icon

## Other
- chore(.net): change framework from .NET 8 to .NET 9

**Full Changelog**: https://github.com/DuckDuckStudio/GitHubView/compare/1.0.3.... .2025.03.07.13718228324
```

Installer(s):
- https://github.com/DuckDuckStudio/GitHubView/releases/download/2025.03.07.13718228324/GitHubView-2025.03.07.13718228324-windows-latest-Setup-SingleFile.exe - inno
- https://github.com/DuckDuckStudio/GitHubView/releases/download/2025.03.07.13718228324/GitHubView-2025.03.07.13718228324-windows-latest.zip - zip + .NET Runtime 9
- https://github.com/DuckDuckStudio/GitHubView/releases/download/2025.03.07.13718228324/GitHubView-2025.03.07.13718228324-windows-latest-SingleFile.exe - portable

```yaml
NestedInstallerType: portable # For zip
  NestedInstallerFiles:
  - RelativeFilePath: output/ghv.exe
# ===============================
ArchiveBinariesDependOnPath: true # For zip & portable
```

> [!NOTE]
> We changed framework from .NET 8 to .NET 9
