### ISSUE TITLE
[Update Request]: DuckStudio.Sundry version 1.0.10

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#237306]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.Sundry

### Package Version

1.0.10

### Please describe the changes you would like to see

Release: https://github.com/DuckDuckStudio/Sundry/releases/tag/1.0.10
Installer (inno): https://github.com/DuckDuckStudio/Sundry/releases/download/1.0.10/Sundry_Setup.exe

> [\!NOTE]
> This issue is created automatically with the build flow, please @DuckDuckStudio for any errors!

---

en-US ReleaseNotes:
```yaml
ReleaseNotes: |-
  Miscellaneous
  - style: Non-fatal error output changed to warning.

  Full Changelog: https://github.com/DuckDuckStudio/Sundry/compare/1.0.9...1.0.10
```
