### ISSUE TITLE
[Update Request]: Rakudo.Rakudo.Star version 2025.02.01

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#242747]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Rakudo.Rakudo.Star

### Package Version

2025.02.01

### Please describe the changes you would like to see

There's a missing package dependency for the manifest. It will lead to infinite error loops of the manifest when launching the main application.

- See <https://github.com/microsoft/winget-pkgs/pull/242027#issuecomment-2746761049>
- Reproduced in <https://github.com/rakudo/star/issues/208#issuecomment-2755183678>
- Identified and resolved in <https://github.com/rakudo/star/issues/208#issuecomment-2755305690>

Following dependencies should be added.

```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```
