### ISSUE TITLE
[Update Request]: kangfenmao.CherryStudio add a new Architecture

### ISSUE THREAD

**Issue by LainZare** [microsoft/winget-pkgs#246442]
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

kangfenmao.CherryStudio

### Package Version

1.1.19

### Please describe the changes you would like to see

**Description:**
In the latest version of CherryStudio (v1.1.19), support for the ARM64 platform has been added. Consequently, the naming convention for the installation packages has been updated. The installation package names have changed from `Cherry-Studio-x.x.x-setup.exe` to `Cherry-Studio-x.x.x-x64-setup.exe` for x64 architecture and `Cherry-Studio-x.x.x-arm64-setup.exe` for ARM64 architecture.

Currently, the manifest file (`manifests/k/kangfenmao/CherryStudio/1.1.19/kangfenmao.CherryStudio.installer.yaml`) lists the ARM64 installer URL for both the user and machine scopes under the x64 architecture section. This causes the ARM64 version to be installed when using winget to install CherryStudio on x64 systems.

**Proposed Solution:**
Update the the manifest file to reference the correct installer URL for the x64 and arm64 architecture.

**Manifest File Affected:**
- `manifests/k/kangfenmao/CherryStudio/1.1.19/kangfenmao.CherryStudio.installer.yaml`

**Current Manifest Content:**
```yaml
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-arm64-setup.exe
  InstallerSha256: 1C0B5663130F77EAC8B2A4AF64744F1964DAB5BBC8099703556426538EB46A76
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-arm64-setup.exe
  InstallerSha256: 1C0B5663130F77EAC8B2A4AF64744F1964DAB5BBC8099703556426538EB46A76
  InstallerSwitches:
    Custom: /allusers
```

**Corrected Manifest Content:**
```yaml
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-x64-setup.exe
  InstallerSha256: <correct-sha256-for-x64-installer>
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-x64-setup.exe
  InstallerSha256: <correct-sha256-for-x64-installer>
  InstallerSwitches:
    Custom: /allusers
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-arm64-setup.exe
  InstallerSha256: <correct-sha256-for-x64-installer>
  InstallerSwitches:
    Custom: /currentuser
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/CherryHQ/cherry-studio/releases/download/v1.1.19/Cherry-Studio-1.1.19-arm64-setup.exe
  InstallerSha256: <correct-sha256-for-x64-installer>
  InstallerSwitches:
    Custom: /allusers
```
