### ISSUE TITLE
[Update Request]: Fortinet.FortiClientVPN - 7.4.3.1790

### ISSUE THREAD

**Issue by jmd-au** [microsoft/winget-pkgs#248236]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Fortinet.FortiClientVPN

### Package Version

7.4.3.1790

### Please describe the changes you would like to see

New release for Fortinet.FortiClientVPN

Download link is: 
https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNInstaller.exe

**Comment by Dragon1573** [comment]
It seems we don't use `FortiClientVPNInstaller.exe` as the installer ...

```yaml
# manifests\f\Fortinet\FortiClientVPN\6.2.0.0780\Fortinet.FortiClientVPN.installer.yaml

InstallerType: exe
InstallerSwitches:
  Silent: /QUIET /NORESTART
  SilentWithProgress: /PASSIVE /NORESTART
Installers:
- Architecture: x64
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_6.2.0_x64.exe
  InstallerSha256: 9202AF4D28A7306645A4B34DEA45EFBCFFE5C94B5DAC8333BC68185B63F88A16
  ProductCode: '{A0B58B60-2749-4D61-BBE1-DB38826EAFBA}'
- Architecture: x86
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_6.2.0.exe
  InstallerSha256: 354E93E1B79AFE1F401F6FCDF5F0D84781C24AA30CC5443BC2C1AC87D1BA0188
  ProductCode: '{A0B58B60-2749-4D61-BBE1-DB38826EAFBA}'
```

```yaml
# manifests\f\Fortinet\FortiClientVPN\6.2.6.0951\Fortinet.FortiClientVPN.installer.yaml

InstallerSwitches:
  Silent: /QUIET /NORESTART
  SilentWithProgress: /PASSIVE /NORESTART
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_6.2.6.0951_x64.exe
  InstallerSha256: 4A0E4D3BB2F969FBBD61D67180604E035D89A44FC1D664B5CBA14368BB3FA671
  ProductCode: '{A43400FD-C5F7-4E6D-B258-E271AB41FC93}'
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_6.2.6.0951.exe
  InstallerSha256: B85F5E9AECC86FF4FBBA25EA064604B48D3CA723FC4AFA7F5CEF3D289E21D84E
  ProductCode: '{A43400FD-C5F7-4E6D-B258-E271AB41FC93}'
```

```yaml
# manifests\f\Fortinet\FortiClientVPN\7.0.1.0083\Fortinet.FortiClientVPN.installer.yaml

InstallerType: zip
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  Custom: /norestart
NestedInstallerType: msi
NestedInstallerFiles:
  - RelativeFilePath: FortiClientVPN.msi
Installers:
- Architecture: x64
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_7.0.1.0083_x64.zip.zip
  InstallerSha256: 1F218F32ABD41C678CC7DBC50A4DA70FBE7C7647518555268A2A55068FC56B96
- Architecture: x86
  InstallerUrl: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNSetup_7.0.1.0083.zip
  InstallerSha256: D0D31562ACA5E3B652DFEF86085D9C72FF6ED0F960F51E44A506FC4AEF7F91B9
```
