### ISSUE TITLE
[Package Issue]: TopalaSoftwareSolutions.SIW version [2025.01.02.1 - 2025.03.25.1] returns 404

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#249840]
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

https://github.com/DuckDuckStudio/winget-tools/actions/runs/14557986998/job/40837522957#step:5:88

### Steps to reproduce

https://github.com/fjwxzde/Test/actions/runs/14560304268/workflow

```yaml
- name: Run Test
  shell: pwsh
  env:
    GITHUB_TOKEN: ${{ github.token }}
  run: |-
    komac list-versions TopalaSoftwareSolutions.SIW | Sort-Object -Descending | `
    ForEach-Object {
      winget download -s winget -e --id TopalaSoftwareSolutions.SIW -d ./Temp -v $_;
      Write-Output ""
    }
```

### Actual behavior

https://github.com/fjwxzde/Test/actions/runs/14560304268/job/40842722334#step:5:4512

### Expected behavior

Normal download.
