### ISSUE TITLE
[Update Request]: KeePassXCTeam.KeePassXC Install location is incorrect

### ISSUE THREAD

**Issue by Maksym-0xp** [microsoft/winget-pkgs#252446]
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

KeePassXCTeam.KeePassXC

### Package Version

2.7.10

### Please describe the changes you would like to see

Adding valid InstallerSwitches would enable use of --location during installation
Currently the KeePassXCTeam.KeePassXC.installer.yaml has 1 Installers with no InstallerSwitches
The default Switchs for InstallLocation (TARGETDIR) is invalid for this package

Test of Public Properties:
❌ .\KeePassXC-2.7.10-Win64.msi TARGETDIR="C:\Applications\KeePassXC"
✅ .\KeePassXC-2.7.10-Win64.msi INSTALL_ROOT="C:\Applications\KeePassXC"

This could be added to the installer yaml to solve this issue:
```yaml
  InstallerSwitches:
    Silent: /quiet /norestart
    SilentWithProgress: /passive /norestart
    Log: /log "<LOGPATH>"
    InstallLocation: INSTALL_ROOT="<INSTALLPATH>"
```
