### ISSUE TITLE
CHIRPSoftware.CHIRP-next installer hash incorrect

### ISSUE THREAD

**Issue by djgraff209** [microsoft/winget-pkgs#256031]
https://github.com/microsoft/winget-pkgs/blob/594ba0f9ad9dba4fdbab57759097b7e33413c313/manifests/c/CHIRPSoftware/CHIRP-next/20250425/CHIRPSoftware.CHIRP-next.installer.yaml#L19

```yaml
Installers:
- Architecture: x64
  InstallerUrl: https://archive.chirpmyradio.com/chirp_next/next-20250425/chirp-next-20250425-installer.exe
  InstallerSha256: CF7BC3013451800AB6832C70E3212E0159B7A6A5207E31700995D72CDF91F41A
```

I pulled this file and ran the command `Get-FileHash` command and received the following:

```pwsh
PS .:\> Get-FileHash -Path .\chirp-next-20250425-installer.exe -Algorithm SHA256

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          53B6874AD7DE5B0F52D33CF656DD21339A22B4229D77E878729941217E6CE957       ....\chirp-…
```
