### ISSUE TITLE
[Package Request]: Mullvad VPN loader

### ISSUE THREAD

**Issue by redactedscribe** [microsoft/winget-pkgs#256463]
### How can we help?

The manifests are below, feel free to submit them without my help.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

I generated the following manifests for the initial release of [Mullvad VPN loader](https://github.com/mullvad/mullvadvpn-app/releases/tag/desktop%2Finstaller-downloader%2F1.0.0) using `wingetcreate` (running loader doesn't install itself anywhere which is why I answered 'y' to whether it is portable):

**Manifest:**

```yaml
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: MullvadVPN.MullvadVPNloader
PackageVersion: 1.0.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
```

**Installer manifest:**

```yaml
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MullvadVPN.MullvadVPNloader
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- mullvad-loader
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mullvad/mullvadvpn-app/releases/download/desktop%2Finstaller-downloader%2F1.0.0/Install.Mullvad.VPN.exe
  InstallerSha256: 4B030A4010F15BC078D3F3CC26EDEE079A764FB197B280891D3DE2AE2E8B1BDF
ManifestType: installer
ManifestVersion: 1.9.0
```

**Locale manifest:**

```yaml
# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: MullvadVPN.MullvadVPNloader
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Mullvad VPN
PublisherUrl: https://mullvad.net/
PublisherSupportUrl: https://mullvad.net/help
PrivacyUrl: https://mullvad.net/en/help/privacy-policy
Author: Mullvad VPN
PackageName: Mullvad VPN loader
PackageUrl: https://github.com/mullvad/mullvadvpn-app/tree/HEAD/installer-downloader
License: GPL-3.0
LicenseUrl: https://github.com/mullvad/mullvadvpn-app/blob/HEAD/LICENSE.md
Copyright: Copyright (C) 2025 Mullvad VPN AB
CopyrightUrl: https://github.com/mullvad/mullvadvpn-app/blob/HEAD/README.md
ShortDescription: Tool for downloading and installing the latest Mullvad VPN app release.
Description: Mullvad VPN loader is available for Windows and macOS, and can install both the latest stable app release as well as the latest beta release. Mullvad VPN loader can be used to update Mullvad VPN whenever a new release is available.
Tags:
- vpn
- installer
- downloader
- open-source
ReleaseNotes: |-
  - Use default font instead of Segoe Fluent Icons for back arrow.
ReleaseNotesUrl: https://github.com/mullvad/mullvadvpn-app/releases/tag/desktop%2Finstaller-downloader%2F1.0.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
```
