### ISSUE TITLE
[Update Request]: AirExplorer.AirExplorer version 5.8.1

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#257371]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AirExplorer.AirExplorer

### Package Version

5.8.1

### Please describe the changes you would like to see

InstallerUrl: https://www.airexplorer.net/downloads/AirExplorer-OnlineInstaller.exe

Komac analyse: 
```yaml
InstallerLocale: en-US
Architecture: x86
InstallerType: nullsoft
Scope: machine
InstallerUrl: https://example.com/
InstallerSha256: 4A420404E11DDFA4B9D1E5D652B5E9BE6B128184F97596C44CA0E216F805A9A0
ProductCode: Air Explorer
AppsAndFeaturesEntries:
- DisplayName: Air Explorer
  Publisher: http://www.airexplorer.net
  DisplayVersion: 5.8.1
  ProductCode: Air Explorer
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\AirExplorer'
```

- Related to https://github.com/microsoft/winget-pkgs/issues/257356#issuecomment-2888195427
