### ISSUE TITLE
[Update Request]: i2van.hourglass 1.15.50

### ISSUE THREAD

**Issue by i2van** [microsoft/winget-pkgs#266021]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

i2van.hourglass

### Package Version

1.15.50

### Please describe the changes you would like to see

New release: 1.15.50

URL: https://github.com/i2van/hourglass/releases/tag/1.15.50
Installer: https://github.com/i2van/hourglass/releases/download/1.15.50/HourglassInstaller.exe

**Comment by UnownPlain** [comment]
I've updated the package in #266028, but I would suggest adding Winget Releaser to your CI to automatically keep your package up to update. Just make sure a PAT called `WINGET_TOKEN` with the `public_repo` scope is added to secrets and this repo is forked under your account. 

Docs: https://github.com/vedantmgoyal9/winget-releaser
Example:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: i2van.hourglass
          token: ${{ secrets.WINGET_TOKEN }}
```
