### ISSUE TITLE
[Package Request]: Argente Utilities

### ISSUE THREAD

**Issue by NewPublicUser** [microsoft/winget-pkgs#266599]
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://argenteutilities.com/en/downloads
Publisher: Raúl Argente
Package Name: Raúl Argente
Description: Windows tools
Package Version: 3.0.1.0 
Installer Url:
Online installer - https://argenteutilities.com/en/download/utilitiesonline
X64 portable - https://argenteutilities.com/en/download/utilitiesx64portable
X64 installer - https://argenteutilities.com/en/download/utilitiesx64
X86 portable - https://argenteutilities.com/en/download/utilitiesx86portable
X86 installer - https://argenteutilities.com/en/download/utilitiesx86
arm64 portable - https://argenteutilities.com/en/download/utilitiesarm64portable
arm64 installer - https://argenteutilities.com/en/download/utilitiesarm64

**Comment by Dragon1573** [comment]
## Manual validation

![Image](https://github.com/user-attachments/assets/75926735-11bc-4f37-9e67-1576e3be9c8a)
![Image](https://github.com/user-attachments/assets/61f5c0cd-4ca5-4de0-82a2-c4cabb86283c)

-----

Hi @NewPublicUser, 👋🏼 

Is there any documentation mentioned about the unattended installation? I can't find any docs on their site ... 😞 

This might be an https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer and can't be supported by `winget.exe`.

-----

Also the downloaded `Argente.Utilities.<arch>.exe` seems a nested downloader. The actual application installer `Argente.Setup.exe` is downloaded elsewhere to a temporary folder.

**Comment by Dragon1573** [comment]
> [!TIP]
> 
> Here's a start point of this package. Anyone can use it. ❤ 

<details><summary><code>manifests/a/Argente/Utilities/3.0.1.0/Argente.Utilities.installer.yaml</code></summary><p>

```yaml
# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Argente.Utilities
PackageVersion: 3.0.1.0
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Argente Installer_is1
ReleaseDate: 2025-06-17
AppsAndFeaturesEntries:
- ProductCode: Argente Installer_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx86
  InstallerSha256: 6FFC5DCD247D7F7AC0740E051541D3ECBFC5E625A47804519545B9B815F34A35
- Architecture: x64
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesx64
  InstallerSha256: C7298E70CBF2ADC2A9069E622C3866C4DA8467B89EFDFA82422AAA42BF7E09E0
- Architecture: arm64
  InstallerUrl: https://argenteutilities.com/en/download/utilitiesarm64
  InstallerSha256: F1D6235D9F86C6B8163A8ADA3194340156E709B9A10CFAC1E09EA98C4AD9125B
ManifestType: installer
ManifestVersion: 1.10.0
```

</p></details>
<details><summary><code>manifests/a/Argente/Utilities/3.0.1.0/Argente.Utilities.locale.en-US.yaml</code></summary><p>

```yaml
# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Argente.Utilities
PackageVersion: 3.0.1.0
PackageLocale: en-US
Publisher: Raúl Argente
PublisherUrl: https://argenteutilities.com/en
PrivacyUrl: https://argenteutilities.com/en#
Author: Raúl Argente
PackageName: Argente Installer
PackageUrl: https://argenteutilities.com/en/downloads
License: Proprietary
# It's in a popup panel instead of a seperate URL.
LicenseUrl: https://argenteutilities.com/en#:~:text=Legal%20conditions
Copyright: Copyright © 2008 - 2025 Raúl Argente
CopyrightUrl: https://argenteutilities.com/en/downloads#:~:text=Copyright
ShortDescription: >
  The choice of more than 13.000.000 users, protects your privacy, fix mistakes
  and make your device faster and safe
ReleaseNotesUrl: https://argenteutilities.com/en/blog#:~:text=ARGENTE%20UTILITIES%203.0.1.0
# Advantages of making a donation:
# - No donation   => Free
# - Over 5 EUR    => Complete
# - Over 15 EUR   => Unlimited
PurchaseUrl: https://argenteutilities.com/en/donate
ManifestType: defaultLocale
ManifestVersion: 1.10.0
```

</p></details>
<details><summary><code>manifests/a/Argente/Utilities/3.0.1.0/Argente.Utilities.yaml</code></summary><p>

```yaml
# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Argente.Utilities
PackageVersion: 3.0.1.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
```

</p></details>
