### ISSUE TITLE
Microsoft.DotNet.DesktopRuntime.7 and Microsoft.DotNet.DesktopRuntime.8 missing installer for machine scope

### ISSUE THREAD

**Issue by DrippyMorshu** [microsoft/winget-pkgs#266862]
### Brief description of your issue

When trying to install .net desktop runtime 7 and 8 under machine scope it fails since there is no installer listed.

Can this be updated?

### Steps to reproduce

winget show Microsoft.DotNet.DesktopRuntime.7 --scope machine outputs:

Found Microsoft .NET Windows Desktop Runtime 7.0 [Microsoft.DotNet.DesktopRuntime.7]
Version: 7.0.20
Publisher: Microsoft Corporation
Moniker: dotnet-desktop-7
Description: .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
Homepage: https://dotnet.microsoft.com
License: MIT
Tags:
  .NET
  .NET Core
  dotnet
  net
  C#
  csharp
  F#
  fsharp
  VB
  Visual Basic
  Windows Desktop
  Windows
  runtime
Installer:
  No applicable installer found; see logs for more details.

### Expected behavior

Winget should return an installer for the machine scope. Below is the output for runtime 6 which has it listed. 

winget show Microsoft.DotNet.DesktopRuntime.6 --scope machine
Found Microsoft .NET Windows Desktop Runtime 6.0 [Microsoft.DotNet.DesktopRuntime.6]
Version: 6.0.36
Publisher: Microsoft Corporation
Moniker: dotnet-desktop-6
Description: .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
Homepage: https://dotnet.microsoft.com
License: MIT
Tags:
  .NET
  .NET Core
  dotnet
  net
  C#
  csharp
  F#
  fsharp
  VB
  Visual Basic
  Windows Desktop
  Windows
  runtime
Installer:
  Installer Type: burn
  Installer Url: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/6.0.36/windowsdesktop-runtime-6.0.36-win-x64.exe
  Installer SHA256: 0d20debb26fc8b2bc84f25fbd9d4596a6364af8517ebf012e8b871127b798941
  Offline Distribution Supported: true

### Actual behavior

Currently winget is unable to find an installer under the machine scope. 
This causes patch integration within our RMM to fail when trying to patch .net via winget.  

### Environment

```shell
Windows: Windows.Desktop v10.0.26100.4351
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.25.390.0
```

**Comment by Dragon1573** [comment]
✅ Proved.

![Image](https://github.com/user-attachments/assets/5b378f58-3e36-46a8-aa5d-91e1e01d9faa)
![Image](https://github.com/user-attachments/assets/04990de6-fe8a-45f7-a9da-ccc753272d50)

-----

Maybe `winget.exe` will only match those installers that explicitly marked `Scope: machine`? This might be a designed, expected behavior.

Both 7 and 8 does not contain this property.

<details><summary><code>manifests/m/Microsoft/DotNet/DesktopRuntime/7/7.0.20/Microsoft.DotNet.DesktopRuntime.7.installer.yaml</code></summary><p>

```yaml
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.DotNet.DesktopRuntime.7
PackageVersion: 7.0.20
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  Custom: /norestart
Installers:
- Architecture: arm64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/7.0.20/windowsdesktop-runtime-7.0.20-win-arm64.exe
  InstallerSha256: 93DF5C5D93D3DEC06B49B555909A751122EDBB3F121D52577578CB9B24FFE4F2
  ProductCode: '{7a58f8fd-40df-4715-b4d5-33bf9e632650}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 7.0.20 (arm64)
    Publisher: Microsoft Corporation
    DisplayVersion: 7.0.20.33720
    ProductCode: '{7a58f8fd-40df-4715-b4d5-33bf9e632650}'
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/7.0.20/windowsdesktop-runtime-7.0.20-win-x64.exe
  InstallerSha256: 57E7C16E7226C9A29DBC3FAEDD9E5876CEC494C7660528052F52160521E7B714
  ProductCode: '{362ea044-f96f-45c7-b59f-0dbe5ca98ff4}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 7.0.20 (x64)
    Publisher: Microsoft Corporation
    DisplayVersion: 7.0.20.33720
    ProductCode: '{362ea044-f96f-45c7-b59f-0dbe5ca98ff4}'
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/7.0.20/windowsdesktop-runtime-7.0.20-win-x86.exe
  InstallerSha256: 58D32D9857BDA5DA99AFC217669AEDACDFFB20AED61F15315718EEB3A455B273
  ProductCode: '{b16df2a0-c74b-4842-a33c-e03a23c6972d}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 7.0.20 (x86)
    Publisher: Microsoft Corporation
    DisplayVersion: 7.0.20.33720
    ProductCode: '{b16df2a0-c74b-4842-a33c-e03a23c6972d}'
ManifestType: installer
ManifestVersion: 1.9.0

```

</p></details>
<details><summary><code>manifests/m/Microsoft/DotNet/DesktopRuntime/8/8.0.17/Microsoft.DotNet.DesktopRuntime.8.installer.yaml</code></summary><p>

```yaml
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
PackageVersion: 8.0.17
MinimumOSVersion: 6.1.7601
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
  Custom: /norestart
Installers:
- Architecture: arm64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.17/windowsdesktop-runtime-8.0.17-win-arm64.exe
  InstallerSha256: 79D68887957DBE719DDC4A2BDBEB344D9B9523CAEE33BE1A9987B1CDA6F0EE4C
  ProductCode: '{696805cf-f28a-4d1f-a85f-eb24505db23d}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 8.0.17 (arm64)
    Publisher: Microsoft Corporation
    DisplayVersion: 8.0.17.34917
    ProductCode: '{696805cf-f28a-4d1f-a85f-eb24505db23d}'
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.17/windowsdesktop-runtime-8.0.17-win-x64.exe
  InstallerSha256: 2EF7C16B285C67FC971919320308F02A39AA5C0EF0F242C3F1EDC364DA65A0E7
  ProductCode: '{5b3e202b-e0c9-4d25-84df-5f687c3b7c47}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 8.0.17 (x64)
    Publisher: Microsoft Corporation
    DisplayVersion: 8.0.17.34917
    ProductCode: '{5b3e202b-e0c9-4d25-84df-5f687c3b7c47}'
- Architecture: x86
  InstallerType: burn
  InstallerUrl: https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0.17/windowsdesktop-runtime-8.0.17-win-x86.exe
  InstallerSha256: 2A92631EB6D6A487F238DA7546C5F287E55EE78773EF730183570CF84F585A20
  ProductCode: '{a62b7c6b-ecc0-430b-a2d2-c4f67e803dc5}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Windows Desktop Runtime - 8.0.17 (x86)
    Publisher: Microsoft Corporation
    DisplayVersion: 8.0.17.34917
    ProductCode: '{a62b7c6b-ecc0-430b-a2d2-c4f67e803dc5}'
ManifestType: installer
ManifestVersion: 1.9.0
```

</p></details>
