### ISSUE TITLE
[Update Request]: DuckStudio.Sundry version 1.2.7

### ISSUE THREAD

**Issue by DuckDuckStudio** [microsoft/winget-pkgs#267655]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.Sundry

### Package Version

1.2.7

### Please describe the changes you would like to see

Release: https://github.com/DuckDuckStudio/Sundry/releases/tag/1.2.7
Installers:
- inno: https://github.com/DuckDuckStudio/Sundry/releases/download/1.2.7/Sundry_Setup.exe
- zip + portable: https://github.com/DuckDuckStudio/Sundry/releases/download/1.2.7/Sundry.zip

> [\!NOTE]
> This issue is created automatically with the build flow, please @DuckDuckStudio for any errors!

**Comment by Dragon1573** [comment]
I've noticed that your [build.yml](https://github.com/DuckDuckStudio/Sundry/blob/main/.github/workflows/build.yml#L140-L147) only contains a step for creating issue in this repository.

```yaml
      - name: 在 winget-pkgs 上创建更新请求
        if: ${{ github.event_name != 'workflow_dispatch' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.ISSUE_TOKEN }}
        # 我也想用模板啊，但是 no templates found.
        run: |
          gh issue create --repo microsoft/winget-pkgs --title "[Update Request]: DuckStudio.Sundry version env.VERSION"−−body"(echo -e "### What type of update are you requesting?\n\nA new version of an existing package\n\n### Current Package Identifier\n\nDuckStudio.Sundry\n\n### Package Version\n\nYou can't use 'macro parameter character #' in math modeYou can't use 'macro parameter character #' in math mode{{ env.VERSION }}\nInstallers:\n- inno: https://github.com/DuckDuckStudio/Sundry/releases/download/env.VERSION/SundrySetup.exe\n−zip+portable:https://github.com/DuckDuckStudio/Sundry/releases/download/{{ env.VERSION }}/Sundry.zip\n\n> [\!NOTE]\n> This issue is created automatically with the build flow, please @DuckDuckStudio for any errors!")"
```

Is it able to also integrate creating pull requests in the workflow, using built **Sundry** itself?
