### ISSUE TITLE
[Package Request]: AvaCC Desktop

### ISSUE THREAD

**Issue by TheRealPear** [microsoft/winget-pkgs#268489]
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.ava.me/download
Publisher: Transcense, Inc.
Package Name: Ava Desktop
Description: Live captions for Deaf and hard-of-hearing people. 
Package Version: 2.1.9
Installer Url: https://ava-tauri-prod.s3.amazonaws.com/app-v2.1.9/AvaCC_2.1.9_x64-setup.exe (the version number changes in the URL, not sure how to account for this)

**Comment by TheRealPear** [comment]
Here's what I have so far. I've not tested these yet but will try to do it on a clean installation of Windows 11. (update: I've tested them and it has passed validations and installs as expected)

<details>
<summary><code>manifests/a/AvaCC/AvaDesktop/2.1.9/AvaCC.AvaDesktop.installer.yaml</code></summary>

```yaml
# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AvaCC.AvaDesktop
PackageVersion: 2.1.9
InstallerType: nullsoft
AppsAndFeaturesEntries:
- Publisher: ava
  ProductCode: AvaCC
Installers:
- Architecture: x64
  InstallerUrl: https://ava-tauri-prod.s3.amazonaws.com/app-v2.1.9/AvaCC_2.1.9_x64-setup.exe
  InstallerSha256: AE9CB44C20CF60D67BECFDA113F907F912F8E8645EFA6076C734A42C00BB54A2
ManifestType: installer
ManifestVersion: 1.9.0
```
</details>

<details>
<summary><code>manifests/a/AvaCC/AvaDesktop/2.1.9/AvaCC.AvaDesktop.locale.en-US.yaml</code></summary>

```yaml
# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AvaCC.AvaDesktop
PackageVersion: 2.1.9
PackageLocale: en-US
Publisher: Transcense, Inc.
PublisherUrl: https://www.ava.me/
PublisherSupportUrl: https://help.ava.me/
PrivacyUrl: https://www.ava.me/privacy
Author: Transcense, Inc.
PackageName: Ava Desktop
PackageUrl: https://www.ava.me/download
License: Proprietary
LicenseUrl: https://www.ava.me/terms
Copyright: © Ava 2024
ShortDescription: Live captions for Deaf and hard-of-hearing people.
Description: |-
  Live captions for Deaf and hard-of-hearing people.   Download Ava on all your devices: smartphone, tablet and computer and enjoy subtitles for all situations. Available 24/7, any time, for any situation.
Moniker: ava
Tags:
- live-captions
- captions
- subtitles
- transcription
- transcriber
- speech-to-text
- deaf
- hard-of-hearing
- ADA
ReleaseNotesUrl: https://ava.canny.io/changelog?labels=desktop-app
ManifestType: defaultLocale
ManifestVersion: 1.9.0
```
</details>

<details>
<summary><code>manifests/a/AvaCC/AvaDesktop/2.1.9/AvaCC.AvaDesktop.yaml</code></summary>

```yaml
# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: AvaCC.AvaDesktop
PackageVersion: 2.1.9
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
```
</details>
