### ISSUE TITLE
Add Minecraft Installer but the publisher should be Mojang Studio or Microsoft or both?

### ISSUE THREAD

**Issue by dinhanhx** [microsoft/winget-pkgs#2899]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: string # the name of the publisher
Name: Minecraft # the name of the application
Version: string # version numbering format
License: copyright Mojang Studios
InstallerType: msi # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x64 # enumeration of supported architectures
    Url: https://launcher.mojang.com/download/MinecraftInstaller.msi # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
