### ISSUE TITLE
Add Tesseract OCR 5.0.0 from UB Mannheim

### ISSUE THREAD

**Issue by dinhanhx** [microsoft/winget-pkgs#2900]
# Package Requested

Manifest:

```YAML
Id: MannheimUniversityLibrary.TesseractOCR
Version: 5.0.0
Name: TesseractOCR
Publisher: MannheimUniversityLibrary
License: Apache License 2.0
LicenseUrl: http://www.apache.org/licenses/LICENSE-2.0
Tags: ocr
Description: Tesseract is an optical character recognition engine for various operating systems. It is free software, released under the Apache License. Originally developed by Hewlett-Packard as proprietary software in the 1980s, it was released as open source in 2005 and development has been sponsored by Google since 2006.
Homepage: https://github.com/UB-Mannheim/tesseract
Arch: x64
Url: https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20200328.exe
Sha256: CCE7A4C94D64345265FDE977DDA952A3480C3D2652E06E675651A2B008B7DF9F
InstallerType: exe
# ManifestVersion: 0.1.0
```
