### ISSUE TITLE
Add Gradle 6.5.1

### ISSUE THREAD

**Issue by jgcodes2020** [microsoft/winget-pkgs#2964]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Gradle.Gradle # publisher.package format
Publisher: Gradle # the name of the publisher
Name: gradle # the name of the application
Version: 6.5.1 # version numbering format
License: Apache v2 # the open source license or copyright
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    #URL of the Gradle zip, other package managers handle installs themselves
    #https://services.gradle.org/distributions/gradle-6.5.1-all.zip 
    Url: # Gradle doesn't have its own installer, it has to be unzipped
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
