### ISSUE TITLE
Add Visual Studio Code System Wide Installer Package

### ISSUE THREAD

**Issue by mhm13dev** [microsoft/winget-pkgs#3201]
I am tagging @lszomoru because he is maintaining the VS Code Package.

As we have packages for `VisualStudioCode` and `VisualStudioCodeInsiders` but they both are the user installers. I want you to please add a System wide installer for both of these packages.

# Package Requested

Manifest: VisualStudioCodeSystem

Fill out as much of the manifest as you can:

```YAML
Id: string # Microsoft.VisualStudioCodeSystem
Publisher: Microsoft Corporation
Name: Visual Studio Code - System Installer
Version: 1.48.1.3dd905126b
License: Copyright (c) Microsoft Corporation
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: string # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
