### ISSUE TITLE
Update MS PowerToys to 0.22.0

### ISSUE THREAD

**Issue by MHacker9404** [microsoft/winget-pkgs#3417]
https://github.com/microsoft/PowerToys/releases/tag/v0.22.0-Experimental

# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: string # the name of the publisher
Name: string # the name of the application
Version: string # version numbering format
License: string # the open source license or copyright
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: string # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
