### ISSUE TITLE
Package Request: Belarc Advisor

### ISSUE THREAD

**Issue by BookWorm0** [microsoft/winget-pkgs#3494]
# Package Requested
See https://www.belarc.com/products_belarc_advisor

Belarc Advisor v9.0 is available from downloads.com. 
See https://download.cnet.com/Belarc-Advisor/3000-2094_4-10007277.html

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: Belarc
Name: Belarc Advisor
Version: 9.0
License: Free for personal home use only
InstallerType: exe
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://files.downloadnow.com/s/software/16/32/54/74/advisorinstaller.exe?token=1599740424_f047f450d2a954ec3e2bc88f93098405&fileName=advisorinstaller.exe
    Sha256: e7cb8844770840dc36964471580aabfc8f7893432e5efc56e4b839d51a6beb6a
# ManifestVersion: 0.1.0
```

**Comment by yigitemres** [comment]
@BookWorm0 

Hi there,

Your manifest needs some corrections. 

> Id: string

This part has to be `Id: Belarc.Advisor`

> License

This part is about EULA.  If you read agreement part of setup you can see that its clearly need to be set `License: Copyright to Belarc Inc.`

> Arch:

I think that its `Arch: x86`.

> Sha256: e7cb8844770840dc36964471580aabfc8f7893432e5efc56e4b839d51a6beb6a

After this part we need to add `Switches`.
```
Sha256: e7cb8844770840dc36964471580aabfc8f7893432e5efc56e4b839d51a6beb6a
    Switches:
      Silent: /s
      SilentWithProgress: /s
```

Wise Installer only use silent switch and don't have any silent with progress switch as I'm aware of.

If you can add these you are good to go except one part. `Url` part have tokens. That means that after some time token expires and download link is become invalid. If you can find any direct link, you manifest file is gonna be approved when you pr. Otherwise, it's gonna be rejected probably.

Lastly, when you pr your file needs to be at this location `manifests\Belarc\Advisor\9.0.yaml`. `Belarc\Advisor` part is needs to be identical to `Id` part and filename must be identical to `Version`.

If you have any question, please ask. Have a nice day! 🥂
