### ISSUE TITLE
[New Feature]: Support android apk files (windows subsystem for anroid, wsa)

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#35340]
### Description of the new feature/enhancement

support android apk as an installer type

### Proposed technical implementation details (optional)

Take AmazeFileExplorer as an example
```
PackageIdentifier: TeamAmaze.AmazeFileManager
PackageVersion: 3.6.7
PackageLocale: en-US
Publisher: TeamAmaze
PackageName: com.amaze.filemanager
License: GPL3
ShortDescription: Simple and attractive Material Design file manager for Android
Installers: 
 - Architecture: arm64
   InstallerType: apk
   InstallerUrl: https://github.com/TeamAmaze/AmazeFileManager/releases/download/v3.6.7/app-fdroid-release.apk
   InstallerSha256: ac25eed953aa2d1fdce3d92e8abe4ded6e89741ec5e43dc3eab102c0c7a1cbe9
ManifestType: singleton
ManifestVersion: 1.0.0
```
