### ISSUE TITLE
Support the installation of Microsoft office

### ISSUE THREAD

**Issue by oxygen-dioxide** [microsoft/winget-pkgs#3813]
Microsoft office is the dependency of jchemforoffice #3785 and jchemforofficelite #3796 .

# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Microsoft.office
Publisher: Microsoft
Name: office
Version: string # version numbering format
License: copyright (c) microsoft
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x64
    Url: string # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
