### ISSUE TITLE
Winget community source database appears to be broken at the moment.

### ISSUE THREAD

**Issue by DrewNaylor** [microsoft/winget-pkgs#4021]
# Brief description of your issue

Manifests such as 7-Zip's don't appear to be showing up, and `winget show 7zip --versions` only shows 7-Zip 16.0.4.

# Steps to reproduce
1. Run `winget show 7zip` and note the output of:
```text
Found 7Zip [7zip.7zip]
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```
2. Run `winget show 7zip --versions` and note that it only shows 16.0.4 even though 19.0.0 used to be there:
```
Version
-------
16.0.4
```

# Expected behavior
The manifests should be showing up here. In this case, 7-Zip should display something like this, or however it's supposed to show up:
```
Found 7Zip [7zip.7zip]
Version: 19.0.0
Publisher: 7zip
Author: 7zip
License: Copyright (C) 1999-2020 Igor Pavlov. - GNU LGPL
LicenseUrl: https://7-zip.org/license.txt
MinOSVersion: 10.0.0.0
Homepage: https://www.7-zip.org/
Description: Free and open source file archiver with a high compression ratio.
Tags: "7zip,compression,file compression,utility,tool,zip"
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://www.7-zip.org/a/7z1900-x64.msi
    Sha256: A7803233EEDB6A4B59B3024CCF9292A6FFFB94507DC998AA67C5B745D197A5DC
    Switches:
      Silent: /quiet /norestart
      SilentWithProgress: /passive /norestart
```

# Actual behavior
It appears that winget can't find the manifests and some versions are messed up. This just started happening at some point after 1 AM EDT on October 8, 2020, so I think it broke during a database update.

# Environment

```none
[winget --info]
Windows Package Manager v0.2.2521 Preview
Windows: Windows.Desktop v10.0.18362.1082
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Any other software?
None that would make a difference in this case.
```
