### ISSUE TITLE
Android SDK Platform-Tools

### ISSUE THREAD

**Issue by Weirdo1312** [microsoft/winget-pkgs#4082]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: Google # the name of the publisher
Name: Android SDK Platform-Tools # the name of the application
Version: 30.0.4 # version numbering format
License: developer.android.com/license # the open source license or copyright
InstallerType: exe (standalone, no installer) # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://dl.google.com/android/repository/platform-tools_r30.0.4-windows.zip # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
