### ISSUE TITLE
"Scrcpy"

### ISSUE THREAD

**Issue by barfin** [microsoft/winget-pkgs#4083]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher:  Genymobile # the name of the publisher
Name: Scrcpy # the name of the application
Version: 1.16 # version numbering format
License:  Apache-2.0 License # the open source license or copyright
InstallerType: EXE (Standalone and depends on android platform cli tools) # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x86,x86_64 # enumeration of supported architectures
    Url: https://github.com/Genymobile/scrcpy/releases # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
