### ISSUE TITLE
[Package Request] AuthPass

### ISSUE THREAD

**Issue by ptanmay143** [microsoft/winget-pkgs#4202]
# Package Requested

Manifest:
Free and Open Source password manager for Android, iOS, macOS, Linux and Windows. Compatible with KeePass.

Fill out as much of the manifest as you can:

```YAML
Id: authpass.authpass # publisher.package format
Publisher: authpass # the name of the publisher
Name: authpass # the name of the application
Version: 1.7.8 # version numbering format
License: GPL-3.0 License # the open source license or copyright
InstallerType: exe # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x86, x64 # enumeration of supported architectures
    Url: https://github.com/authpass/authpass/releases/download/v1.7.8/AuthPass-setup-1.7.8_1552.exe # path to download installation file
    Sha256: 815D85A04340FF9BA964085FE51520048117DA82C5F5EC786FD35188EEBA36BC # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
