### ISSUE TITLE
[Package Request] MusicBee

### ISSUE THREAD

**Issue by zvwwe** [microsoft/winget-pkgs#4216]
# Package Requested

Manifest:
MusicBee makes it easy to manage, find, and play music files on your computer. MusicBee also supports podcasts, web radio stations and SoundCloud integration.

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: MusicBee # the name of the publisher
Name: MusicBee # the name of the application
Version: 3.3.7491 # version numbering format
License: string # the open source license or copyright
InstallerType: exe # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x86, x64 # enumeration of supported architectures
    Url: https://www.mediafire.com/file/q7xbxr7hipn1ccu/MusicBeeSetup_3_3_Update6.zip/file # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
