### ISSUE TITLE
[Package Request] Just

### ISSUE THREAD

**Issue by vmiheer** [microsoft/winget-pkgs#4413]
# Just

Manifest:
```YAML
Id: casey.just
Publisher: casey
Name: just
Version: 0.8.1
License: Creative Commons Legal Code
InstallerType: zip
Installers:
  - Arch: x64
    Url: https://github.com/casey/just/releases/download/v0.8.1/just-v0.8.1-x86_64-pc-windows-msvc.zip
    Sha256: 22E2D14EDBF76DDA21358C61392A7CC4041B20D60847F1D89FB4B5EDB665D2EF
ManifestVersion: 0.0.1
```
