### ISSUE TITLE
Have

### ISSUE THREAD

**Issue by vero555** [microsoft/winget-pkgs#4569]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: string # the name of the publisher
Name: string # the name of the application
Version: string # version numbering format
License: string # the open source license or copyright
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: string # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
