### ISSUE TITLE
[Package Request] IPFS

### ISSUE THREAD

**Issue by FireMasterK** [microsoft/winget-pkgs#4594]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: IPFS.IPFS-Desktop # publisher.package format
Publisher: IPFS-Desktop # the name of the publisher
Name: IPFS # the name of the application
Version: 0.13.2 # version numbering format
License: MIT # the open source license or copyright
InstallerType: exe # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x64 # enumeration of supported architectures
    Url: https://github.com/ipfs-shipyard/ipfs-desktop/releases/download/v0.13.2/IPFS-Desktop-Setup-0.13.2.exe # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```
