### ISSUE TITLE
[Bug]: Unable to validate a new package

### ISSUE THREAD

**Issue by svanimpe** [microsoft/winget-pkgs#46097]
### Brief description of your issue

I've created a new package (new version of `Swift.Toolchain`) using the `YamlCreate` script. However, I am unable to validate this package.

The command `winget validate --manifest Swift.Toolchain.yaml` fails saying the multi-file manifest is incomplete.

I've also tried to use the Windows Sandbox as suggested here: https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md but the command `Enable-WindowsOptionalFeature -FeatureName "Containers-DisposableClientVM" -All -Online` prints an error saying the feature named Containers-DisposableClientVM is unknown.

### Steps to reproduce

Manifest files:

**Swift.Toolchain.yaml**:

```
# Created with YamlCreate.ps1 v2.0.7 $debug=NVS1.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Swift.Toolchain
PackageVersion: 5.5.3
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
```

**Swift.Toolchain.installer.yaml**:

```
# Created with YamlCreate.ps1 v2.0.7 $debug=NVS1.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Swift.Toolchain
PackageVersion: 5.5.3
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: burn
Scope: machine
UpgradeBehavior: uninstallPrevious
Commands:
- swift
FileExtensions:
- swift
ReleaseDate: 2022-02-09
Installers:
- Architecture: x64
  InstallerUrl: https://download.swift.org/swift-5.5.3-release/windows10/swift-5.5.3-RELEASE/swift-5.5.3-RELEASE-windows10.exe
  InstallerSha256: A545F0404C13D45B8D7CA257C1395FF01938786EA5730E27E570EB0486B7079F
ManifestType: installer
ManifestVersion: 1.1.0
```

**Swift.Toolchain.locale.en-US.yaml**:

```
# Created with YamlCreate.ps1 v2.0.7 $debug=NVS1.7-2-1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Swift.Toolchain
PackageVersion: 5.5.3
PackageLocale: en-US
Publisher: dt.compnerd.org
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
Author: Swift Open Source Project
PackageName: Swift
PackageUrl: https://www.swift.org/
License: Apache License 2.0
LicenseUrl: https://github.com/apple/swift/blob/main/LICENSE.txt
Copyright: Copyright (c) Swift Open Source Project
# CopyrightUrl: 
ShortDescription: Swift Toolchain for Windows
# Description: 
Moniker: swift
Tags:
- swift
# Agreements: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
ManifestType: defaultLocale
ManifestVersion: 1.1.0
```

### Expected behavior

I would expect files generated by `YamlCreate` to validate.

### Actual behavior

See above

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.493
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```
