### ISSUE TITLE
[Package Request]: Zoom 64-Bit 

### ISSUE THREAD

**Issue by thedoggybrad** [microsoft/winget-pkgs#46241]
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Zoom Video Communications Inc.
Publisher Url: https://zoom.us/download
Package Name: Zoom Meeting Client (64-Bit)
Description: Zoom Meetings is a proprietary video teleconferencing software program developed by Zoom Video Communications.
Package Version: 5.9.3
Installer URL: https://cdn.zoom.us/prod/5.9.3.3169/x64/ZoomInstaller.exe

Current Package Identifier (for new versions):

**Comment by Trenly** [comment]
The 64-bit version of zoom is already available. `winget install Zoom.Zoom`
```yaml
PackageIdentifier: Zoom.Zoom
PackageVersion: 5.9.3169
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2021-01-25
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.zoom.us/prod/5.9.3.3169/x64/ZoomInstallerFull.msi
  InstallerSha256: 886A4488F7611BD75CAA5909F985AFA6043AF48E1C8A54C915A4206D563BA18E
  ProductCode: '{E5F9EFAB-11E7-48E4-B8E7-B3614E5FFCE0}'
- Architecture: x86
  InstallerUrl: https://cdn.zoom.us/prod/5.9.3.3169/ZoomInstallerFull.msi
  InstallerSha256: 04C4D3EAA4F340BDD9E4E15A555AE0FC6053AC2F678E362F5E7D53FD358A77A6
  ProductCode: '{ED7ECCC4-7251-4BE2-9E0A-B98D8B0DC446}'
ManifestType: installer
ManifestVersion: 1.1.0
```
