### ISSUE TITLE
Update for Microsoft.VC++2015-2019Redist packages

### ISSUE THREAD

**Issue by lychichem** [microsoft/winget-pkgs#4798]
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Microsoft.VC++2015-2019Redist-x86
Publisher: Microsoft Corporation
Name: Microsoft Visual C++ 2015-2019 Redistributable (x86)
Version: 14.28.29325.2
License: Copyright (c) Microsoft Corporation
InstallerType: exe
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://aka.ms/vs/16/release/vc_redist.x86.exe
    Sha256: 50A3E92ADE4C2D8F310A2812D46322459104039B9DEADBD7FDD483B5C697C0C8
# ManifestVersion: 0.1.0
```

```YAML
Id: Microsoft.VC++2015-2019Redist-x64
Publisher: Microsoft Corporation
Name: Microsoft Visual C++ 2015-2019 Redistributable (x64)
Version: 14.28.29325.2
License: Copyright (c) Microsoft Corporation
InstallerType: exe
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://aka.ms/vs/16/release/vc_redist.x64.exe
    Sha256: B1A32C71A6B7D5978904FB223763263EA5A7EB23B2C44A0D60E90D234AD99178
# ManifestVersion: 0.1.0
```

As they are MS maintain packages, I can't find a place to add them in this repo. Please update them.
