### ISSUE TITLE
Auto generate manifests for newer versions

### ISSUE THREAD

**Issue by felipecassiors** [microsoft/winget-pkgs#500]
# Disclaimer

I tried to find an issue like this in both repositories, but I didn't.

# Description of the new feature/enhancement

To support some kind of CI that, based on previously set logic, can auto-generate manifests for newer versions of the packages.

# Proposed technical implementation details

A very good example is the Chocolatey Automatic Package Updater Module: https://github.com/majkinetor/au

Based on custom rules, such as scripts for finding newer versions, URLs for downloading them, a CI can run continuously based on a scheduled trigger, and if it finds a newer version, it try to build a new manifest automatically, test it, and submit a PR (or push directly).

So then, we don't need to manually create manifests for every new version of an existing package.

**Comment by superusercode** [comment]
Scoop also has their own implementation of this: https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate

**Comment by felipecassiors** [comment]
If we settle on an implementation archtecture I think the community would be excited to help. **I also think this is something to put on the v1 backlog.**

I was thinking of something like:

Every package (which has its own folder inside the `Publisher`) can have a file called `update.yml`. This file can be like

``` YAML  
template:
  Id: GitHub.cli
  Name: GitHub CLI
  AppMoniker: gh
  InstallerType: MSI
updaters:
  - arch: x64
     uses: updater-github-releases
     with: 
       regex: '*_windows_amd64.msi'
  - arch: x86
     uses: updater-github-releases
     with:
       regex: '*_windows_386.msi'
```

And then, `updater-github-releases` would be a plugin for the packages delivered through GitHub Releases. 

This enables people to create every kind of plugin, and this way making them reusable without having to share code. People could create plugins which are applicable for a single distributor, but for that case, we can also have an extremely generic plugin, such as `updater-html-webscrap`:

``` YAML
updaters:
  - arch: x64
     uses: updater-html-webscrap
     with:
       versionFilter: '.list-group-item:contains(version)'
       url: https://contoso.com/download
       downloadUrl: "https://contoso.com/download/contoso_${{ version }}.msi"
```

These plugins must return some values, such as `version`, `x64.url`, and `x64.hash` for instance.

These plugins could be `npm` modules for easy management.
