### ISSUE TITLE
Request to add CNCOnline Launcher

### ISSUE THREAD

**Issue by AlJohri** [microsoft/winget-pkgs#5658]
# Package Requested

C&C:Online Launcher
https://cnc-online.net/en/download/
http://server.cnc-online.net/downloads/cnconline/CNCOnline_2.0.7.msi

```
PS C:\Users\aljoh\Downloads> Get-FileHash -Path .\CNCOnline_2.0.7.msi -Algorithm SHA256

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          B9912C97500F7E4DED5A7E343FB97D71620D0E8C69837C3D1063EF90D79DDE67       C:\Users\aljoh\Downloads\CNCO...
```

--

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Revora.CNCOnline
Publisher: Revora
Name: CNCOnline
Version: 2.0.7
License: string # the open source license or copyright
InstallerType: msi
Installers:
  - Arch: string # enumeration of supported architectures
    Url: http://server.cnc-online.net/downloads/cnconline/CNCOnline_2.0.7.msi
    Sha256: B9912C97500F7E4DED5A7E343FB97D71620D0E8C69837C3D1063EF90D79DDE67
# ManifestVersion: 0.1.0
```
