### ISSUE TITLE
Request to add Logitech Options

### ISSUE THREAD

**Issue by AlJohri** [microsoft/winget-pkgs#5665]
# Package Requested

Logitech Options
https://www.logitech.com/en-us/product/options
https://download01.logi.com/web/ftp/pub/techsupport/options/Options_8.36.86.exe

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          746C52C46C9E57D2C20922A4D9C5E11A1847AC24916A59ABFBC528235A356946       C:\Users\aljoh\Downloads\Opti...
```

I wasn't sure if this one was exe or inno so I left it blank. for now. From Choclatey it seems like it would be exe: https://chocolatey.org/packages/logitech-options#files

Any easy way to check?

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Logitech.Options
Publisher: Logitech
Name: Options
Version: 8.36.86
License: string # the open source license or copyright
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://download01.logi.com/web/ftp/pub/techsupport/options/Options_8.36.86.exe
    Sha256: 746C52C46C9E57D2C20922A4D9C5E11A1847AC24916A59ABFBC528235A356946
# ManifestVersion: 0.1.0
```
