### ISSUE TITLE
Request to add Duet Display

### ISSUE THREAD

**Issue by AlJohri** [microsoft/winget-pkgs#5666]
# Package Requested

Duet Display
https://www.duetdisplay.com/
`https://updates.duetdisplay.com/latestWindows` -> `https://duet.nyc3.cdn.digitaloceanspaces.com/Windows/1_9/DuetSetup-1-9-2-7.exe`

```
PS C:\Users\aljoh\Downloads> Get-FileHash -Path .\DuetSetup-1-9-2-7.exe -Algorithm SHA256

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          0DEB24426F8FF8C161F96988C4FB9DA857232A61D21881382C93EE579A7B9515       C:\Users\aljoh\Downloads\DuetSetup-1-9-2-7.exe
```

This one seems like a non-standard exe? I tried passing `/?` and got these results:

![image](https://user-images.githubusercontent.com/2790092/102886861-e6b38180-4423-11eb-9f44-7c35f909813e.png)

It mentions `msiexec` though so I imagine it should be compatible?

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: Kairos.DuetDisplay
Publisher: Kairos
Name: DuetDisplay
Version: 1.9.2.7
License: string # the open source license or copyright
InstallerType: string # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://duet.nyc3.cdn.digitaloceanspaces.com/Windows/1_9/DuetSetup-1-9-2-7.exe
    Sha256: 0DEB24426F8FF8C161F96988C4FB9DA857232A61D21881382C93EE579A7B9515
# ManifestVersion: 0.1.0
```
