### ISSUE TITLE
[Package request] CorsixTH

### ISSUE THREAD

**Issue by tobylane** [microsoft/winget-pkgs#5859]
# Package Requested

Manifest:

```YAML
Id: corsixth.corsixth
Publisher: corsixth
Name: CorsixTH
AppMoniker: corsix-th
Version: 0.64
License: MIT
Description: A reimplementation of the 1997 Bullfrog business sim Theme Hospital. As well as faithfully recreating the original, CorsixTH adds support for modern operating systems (Windows, macOS, Linux and BSD), high resolutions and much more.
Homepage: https://github.com/CorsixTH/CorsixTH
Tags: game, gaming, theme hospital, simulation, hospital
Commands: corsixth, corsix-th
InstallerType: nullsoft
Switches:
  Silent: /s
Installers:
  - Arch: neutral # x86 and x64
    Url: https://github.com/CorsixTH/CorsixTH/releases/download/v0.64/CorsixTHInstaller.exe
    Sha256: cd232ac70e7f4e82b616868a1cac12f522675377f39c3f8e941b758c71a5999b
# ManifestVersion: 0.1.0
```
I don't understand if the silent switch is guessed from the installer type or not. Hope this works.
