### ISSUE TITLE
[Package Request]: 3DConnexion 3DxWare

### ISSUE THREAD

**Issue by myokeeh** [microsoft/winget-pkgs#69146]
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 3DConnexion
Publisher Url: https://3dconnexion.com/
Package Name: 3DxWare 
Description: SpaceMouse Software and Drivers
Package Version: 10.8.8
Installer URL: https://download.3dconnexion.com/drivers/win/10-8-8_F62EDF4A-E000-4661-AD52-494401F99663/3DxWare64_v10-8-8_r3488.exe

Current Package Identifier (for new versions):

**Comment by TheBossMagnus** [comment]
So, the app fails to install without user input. Help is needed for silent switches...

**Comment by Trenly** [comment]
@TheBossMagnus try this -
```yaml
InstallerSwitches: 
  Silent: /install /quiet
  SilentWithProgress: /install /passive
  Custom: /norestart
  InstallLocation: InstallFolder="<INSTALLPATH>"
  Log: /log <LOGPATH>
```
