### ISSUE TITLE
Cuda toolkit

### ISSUE THREAD

**Issue by vmiheer** [microsoft/winget-pkgs#6946]
# Package Requested

Manifest:

```YAML
Id: Nvidia.cuda
Name: Nvidia cuda toolkit
Version: 3.20.3.63
Publisher: Nvidia
Homepage: https://www.nvidia.com/
Description: Artificial Intelligence Computing Leadership from NVIDIA
License: Copyright © 2020 NVIDIA Corporation
LicenseUrl: https://docs.nvidia.com/cuda/eula/index.html
InstallerType: Exe
Switches:
  Custom:  -s nvcc_11.2 cuobjdump_11.2 nvprune_11.2 cupti_11.2 memcheck_11.2 nvdisasm_11.2 nvprof_11.2 visual_profiler_11.2 visual_studio_integration_11.2 nsight_vse_11.2 nsight_nvtx_11.2 demo_suite_11.2 documentation_11.2 cublas_11.2 cublas_dev_11.2 cudart_11.2 cufft_11.2 cufft_dev_11.2 curand_11.2 curand_dev_11.2 cusolver_11.2 cusolver_dev_11.2 cusparse_11.2 cusparse_dev_11.2 npp_11.2 npp_dev_11.2 nvrtc_11.2 nvrtc_dev_11.2 nvml_dev_11.2 occupancy_calculator_11.2 samples_11.2 Display.Driver
Installers:
  - Arch: x64
    Url: https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda_11.2.0_460.89_win10.exe
    Sha256: da1dc049663a82fbf4d046337d5660f9dd9e2f58d50a619dec1ad49a9ddb614b
```

Issues: This manifest is more or less complete but when installing with winget using `winget install -m` it errors out. I have no idea how to debug the error. I would really appreciate any help. Also, it would be good to have winget cache for packages, the cuda package is 2.2 GB. And downlaoding such a large package again and again for debugging is bad.

If I use below command line in powershell, the silent install runs fine.

```powershell
cmd /c .\cuda_11.2.0_460.89_win10.exe -s nvcc_11.2 cuobjdump_11.2 nvprune_11.2 cupti_11.2 memcheck_11.2 nvdisasm_11.2 nvprof_11.2 visual_profiler_11.2 visual_studio_integration_11.2 nsight_vse_11.2 nsight_nvtx_11.2 demo_suite_11.2 documentation_11.2 cublas_11.2 cublas_dev_11.2 cudart_11.2 cufft_11.2 cufft_dev_11.2 curand_11.2 curand_dev_11.2 cusolver_11.2 cusolver_dev_11.2 cusparse_11.2 cusparse_dev_11.2 npp_11.2 npp_dev_11.2 nvrtc_11.2 nvrtc_dev_11.2 nvml_dev_11.2 occupancy_calculator_11.2 samples_11.2 Display.Driver
```
