### ISSUE TITLE
[Package Request] flameshot

### ISSUE THREAD

**Issue by ZetaoYang** [microsoft/winget-pkgs#7072]
### Powerful yet simple to use screenshot software
https://github.com/flameshot-org/flameshot

Manifest:

```YAML
Id: Flameshot.Flameshot
Publisher: Flameshot
Name: Flameshot
AppMoniker: flameshot
Version: 0.8.4
License: GPL-3.0 License
LicenseUrl: https://github.com/flameshot-org/flameshot/blob/master/LICENSE
Tags: screenshot, snipping, capture
Description: Powerful yet simple to use screenshot software.
Homepage: https://flameshot.org
Installers:
  - Arch: x86
    Url: https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win32.msi
    Sha256: 0D23E5A5C029B1D195410B84BFEFD551784741657F60C47142CBF0640419CEDF
    InstallerType: msi
    Switches:
      Silent: /passive
  - Arch: x64
    Url: https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win64.msi
    Sha256: 91CB939D440D8A00ACDBB995177E88ACBBB0609E69C2ABA471883D11A0A3AC67
    InstallerType: msi
    Switches:
      Silent: /passive
ManifestVersion: 0.1.0
```
