### ISSUE TITLE
Improve License Information in manifest

### ISSUE THREAD

**Issue by swaldhoer** [microsoft/winget-pkgs#855]
# Description of the new feature/enhancement

Projects that are hosted on some kind of services that allows browsing the sources should include the exact license information not only the generic link to the project license.

# Proposed technical implementation details (optional)

Where possible the versions exact license file should be linked, as license may (and they do) change during a project.

I think adding a entry to the *.yaml would solve this issue:

Example for the [git package](https://github.com/microsoft/winget-pkgs/blob/a20c7e0e427c5cf76d1f494e44cc177911bcee26/manifests/Git/Git/2.26.2.yaml):

The project has an accessible repository for its releases (not only a zip release). We add a key ``ExactLicenseUrl`` and the manifest would look like this:

```yaml
# ...
Homepage: https://git-scm.com/
License: GNU General Public License, version 2
ExactLicenseUrl: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/COPYING
LicenseUrl: https://github.com/git-for-windows/git/blob/master/COPYING
Description: Git version control system.
InstallerType: Inno
# ...
```

And now you can see general license information which might be interesting, but the more important thing, you now know the license of the version you are currently using.

**Comment by jamierocks** [comment]
Given the manifests are for specific versions, I think its reasonable to use the exact URL for manifests - without the need for another key.

```yaml
# ...
Homepage: https://git-scm.com/
License: GNU General Public License, version 2
LicenseUrl: https://github.com/git-for-windows/git/blob/v2.26.2.windows.1/COPYING
Description: Git version control system.
InstallerType: Inno
# ...
```
