### ISSUE TITLE
Equalizer APO (x64)

### ISSUE THREAD

**Issue by labo89** [microsoft/winget-pkgs#9186]
# Package Requested

Manifest:

```YAML
Id: jthedering.equalizerapo
Publisher: jthedering
Name: Equalizer APO (x64)
Version: 1.2.1
License: GNU General Public License version 2.0 (GPLv2)
InstallerType: Nullsoft
Installers:
  - Arch: x64
    Url: https://altushost-swe.dl.sourceforge.net/project/equalizerapo/1.2.1/EqualizerAPO64-1.2.1.exe
    Sha256: BD0AC49633D02A387F906B5D4F47F9235D229470742D3433018245136756F583
ManifestVersion: 0.1.0
```
