### ISSUE TITLE
[Package Issue]: Dropbox.Dropbox - winget "upgrades" 64-bit version of Dropbox to 32-bit version

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/winget-pkgs#93678]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I am currently running 64-bit Dropbox, downloaded directly from them:
`https://www.dropbox.com/downloading?plat=win&type=full&arch=x64`

the current installer from that link is ...
`https://edge.dropboxstatic.com/dbx-releng/client/experimental/Dropbox%20164.4.7914%20Offline%20Installer.x64.exe`

please note that their own installer has put the 64-bit executable in the `C:\Program Files (x86)\Dropbox\` folder, it was not my choice to put it there.

...and... it seems that winget is trying to replace a 64-bit version of Dropbox with a 32-bit one - the installer that winget is trying to download has no "x64" in the url - for Dropbox that usually means it is a x86 executable image, not an x64

![image](https://user-images.githubusercontent.com/16319504/212397611-a0085886-b3be-406c-b583-a016cac49f03.png)

### Steps to reproduce

- install the 64-bit version of Dropbox 
e.g. `https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20164.4.7914%20Offline%20Installer.x64.exe`
- run winget upgrade
- find out that winget is trying to replace the 64-bit build with a 32-bit one.

### Actual behavior

winget wants to "upgrade" my Dropbox from 64-bit to 32-bit.

### Expected behavior

install the x64 upgrade, not the x86 one

### Environment

```shell
PS C:\WINDOWS\system32> winget --info
Windows Package Manager (Preview) v1.5.101-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.101.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale


PS C:\WINDOWS\system32> winget list dropbox.dropbox
Name    Id              Version    Available  Source
----------------------------------------------------
Dropbox Dropbox.Dropbox 164.4.7914 165.4.4300 winget
PS C:\WINDOWS\system32> winget show dropbox.dropbox
Found Dropbox [Dropbox.Dropbox]
Version: 165.4.4300
Publisher: Dropbox, Inc.
Publisher Url: https://www.dropbox.com
Publisher Support Url: https://help.dropbox.com
Author: Dropbox, Inc.
Moniker: dropbox
Description: Organize all your team's content, tune out distractions, and get everyone coordinated with the world's first smart workspace.
Homepage: https://www.dropbox.com
License: Combined GPLv2 and proprietary software
License Url: https://www.dropbox.com/terms
Privacy Url: https://www.dropbox.com/privacy
Copyright: Copyright (c) Dropbox, Inc.
Copyright Url: https://www.dropbox.com/terms
Tags:
  cloud
  dropbox
  files
  online
  pictures
  storage
Installer:
  Installer Type: nullsoft
  Installer Url: https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20165.4.4300%20Offline%20Installer.exe
  Installer SHA256: 6afe5324e7d2c18d565b2e5bbd98853c8ccd44da3f0dce03608b54dbbbca6d1f
  Release Date: 2023-01-12
```

**Comment by R-Adrian** [comment]
note: i let winget do its thing and actually run the upgrade... i was right, the "upgraded" Dropbox executable after that is 32-bit now. (window border is different colour because of desktop theme change)

![image](https://user-images.githubusercontent.com/16319504/212399823-4e56d4c2-ad4b-4132-9254-b0739bde7066.png)

**Comment by R-Adrian** [comment]
P.S.
also, looking at the manifest file used by winget, seems the same file (same SHA-256 checksum) is listed for both x64 and x86 installers.  
Assuming this is not a SHA-256 collision between different files, this indicates they are actually the same installer.

In the problem description above winget correctly shows the URL for what it thinks is the x64 installer (the one without x86 in the name), but the problem is caused by the fact this is actually the same x86 installer, but with a different url.


```
UpgradeBehavior: install
ReleaseDate: 2023-01-12
Installers:
- Architecture: x64
  InstallerUrl: https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20165.4.4300%20Offline%20Installer.exe
  InstallerSha256: 6AFE5324E7D2C18D565B2E5BBD98853C8CCD44DA3F0DCE03608B54DBBBCA6D1F
- Architecture: x86
  InstallerUrl: https://edge.dropboxstatic.com/dbx-releng/client/Dropbox%20165.4.4300%20Offline%20Installer.x86.exe
  InstallerSha256: 6AFE5324E7D2C18D565B2E5BBD98853C8CCD44DA3F0DCE03608B54DBBBCA6D1F
ManifestType: installer
ManifestVersion: 1.2.0
```
