### ISSUE TITLE
[New Feature]: Dependencies in the manifest

### ISSUE THREAD

**Issue by Chaython** [microsoft/winget-pkgs#94368]
### Description of the new feature/enhancement

There should be the ability to write dependencies in the manifest, rather than needing to add redistributable/downloaders into the installers themselves. For example, better discord is dependent on discord but doesn't install it. Yet would be convenient to have in winget.

**Comment by Trenly** [comment]
Close with reason: This feature is already in experimental support; See https://github.com/microsoft/winget-cli/issues/163

Manifests which require dependencies to install properly will remain blocked until the feature is in stable.

Usage (in installer manifest):
```
Dependencies:
  PackageDependencies:
    - PackageIdentifier:
      MinimumVersion:
```
