### ISSUE TITLE
[Package Issue]: Ghisler.TotalCommander

### ISSUE THREAD

**Issue by chbwien** [microsoft/winget-pkgs#94605]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget installs the x64 Version on an arm64 Windows. Hence it does not work, because arm64 supports only 32 Bit exes

### Steps to reproduce

winget install Ghisler.TotalCommander 
on an arm64 Windows installs the x64 version.

### Actual behavior

the x64 version is installed on an arm64 Windows

### Expected behavior

the x86 (32 bit) version should be installed on arm64

### Environment

```shell
Windows-Paket-Manager v1.4.10173
```

**Comment by stephengillie** [comment]
Reviewing the [most recent PR](https://github.com/microsoft/winget-pkgs/pull/87632/files), arm64 isn't listed as an installer architecture, but `x86`, `x64`, and `neutral` (which appears to be for both and might also be 32-bit) are listed. I'm guessing the behavior in this situation might be based on Winget defaults. As a workaround, could you try manually specifying the installer architecture? 

`winget install Ghisler.TotalCommander --architecture x86` 
- I don't have an ARM system to test this on, but I'm hopeful that this will work.

**Comment by mdanish-kh** [comment]
IIRC neutral includes all architectures so the author is probably getting [this URL](https://github.com/microsoft/winget-pkgs/blob/7e8e0d30c1ef68a6e10d93995e3d4b0015f08b3a/manifests/g/Ghisler/TotalCommander/10.52/Ghisler.TotalCommander.installer.yaml#L13). 
@chbwien Can you share which Url you're getting through `winget show Ghisler.TotalCommander`?

If installing the x86 works out for you through the command stephengillie shared, the manifest can be modified to use x86 Url for arm64 architecture.

**Comment by chbwien** [comment]
Sorry for the delay, it was getting late and then things to work on.
Here the installed version info of the Arm System:
```
Windows-Paket-Manager v1.3.2691
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.1105
Systemarchitektur: Arm64
Paket: Microsoft.DesktopAppInstaller v1.18.2691.0
```

And here the result of the show command
```
PS C:\Users\CHB> winget show Ghisler.TotalCommander
Gefunden Total Commander [Ghisler.TotalCommander]
Version: 10.52
Herausgeber: Ghisler Software GmbH
Herausgeber-URL: https://www.ghisler.com/deutsch.htm
Herausgeber-Support-URL: https://www.ghisler.com/dfaq.htm
Autor: Christian Ghisler
Moniker: tcmd
Beschreibung: Total Commander ist ein Filemanager mit Plugin-Unterstuetzung im klassischen 2-Fenster-Stil des Norton Commanders
Startseite: https://www.ghisler.com/deutsch.htm
Lizenz: Shareware
Lizenz-URL: https://www.ghisler.com/dorder.htm
Datenschutz-URL: https://www.ghisler.com/datenschutzerklaerung.htm
Copyright: Copyright (c) Christian Ghisler
URL der Versionshinweise: https://www.ghisler.com/mailingd.htm
Installationsprogramm:
  Typ: exe
  Download-URL: https://totalcommander.ch/win/tcmd1052x64.exe
  SHA256: 3cfcbfe6dff0eb24726183595f771f2a8acb0534e2240bef75c0800546a575eb
  Freigabedatum: 2022-10-26
```

**Comment by chbwien** [comment]
I have just upgraded winget manually, so the version reads now

```
PS C:\Users\CHB> winget --info
Windows-Paket-Manager v1.4.10173
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

Windows: Windows.Desktop v10.0.22621.1105
Systemarchitektur: Arm64
Paket: Microsoft.DesktopAppInstaller v1.19.10173.0
```

But the result is unchanged

```
PS C:\Users\CHB> winget show Ghisler.TotalCommander
Gefunden Total Commander [Ghisler.TotalCommander]
Version: 10.52
Herausgeber: Ghisler Software GmbH
Herausgeber-URL: https://www.ghisler.com/deutsch.htm
Herausgeber-Support-URL: https://www.ghisler.com/dfaq.htm
Autor: Christian Ghisler
Moniker: tcmd
Beschreibung: Total Commander ist ein Filemanager mit Plugin-Unterstuetzung im klassischen 2-Fenster-Stil des Norton Commanders
Startseite: https://www.ghisler.com/deutsch.htm
Lizenz: Shareware
Lizenz-URL: https://www.ghisler.com/dorder.htm
Datenschutz-URL: https://www.ghisler.com/datenschutzerklaerung.htm
Copyright: Copyright (c) Christian Ghisler
URL der Versionshinweise: https://www.ghisler.com/mailingd.htm
Markierungen:
  filemanager
  file-manager
Installationsprogramm:
  Installertyp: exe
  Installer-URL: https://totalcommander.ch/win/tcmd1052x64.exe
  Sha256-Installer: 3cfcbfe6dff0eb24726183595f771f2a8acb0534e2240bef75c0800546a575eb
  Freigabedatum: 2022-10-26
```
