### ISSUE TITLE
[New Feature]: Superseding packages

### ISSUE THREAD

**Issue by heaths** [microsoft/winget-pkgs#95553]
### Description of the new feature/enhancement

When packages get renamed - branding, ownership, for whatever reason - having a supersedence story is important so that, for example, Bar v2 can replace Foo v1. There's nothing stopping any package from doing this already e.g., an MSI with an appropriate Upgrade table can easily replace any other MSI, but having these then-errant package manifests installed could be confusing both to the user and possibly to _winget_ itself. I imagine, for example, this could be a problem for https://github.com/microsoft/winget-cli/issues/2634.

### Proposed technical implementation details (optional)

Similar in concept to the Windows Installer Upgrade table (though not using GUIDs), a version manifest could define something like:

```yaml
replaces: # could also use "supersedes" or "deprecates"
- id: Foo
  minVersion: 1 # optional
  maxVersion: 2 # optional
  # possibly language, arch, etc. specifiers here, but not sure how useful those are in practice
```

Alternatively, the old package could reference the new package [like choco does](https://docs.chocolatey.org/community-repository/maintainers/deprecate-a-chocolatey-package#the-solution), but without ownership protections in place already for manifests here, it seems unnecessary to publish a new version of the old package when the new package can just say they replace the old package.

Note: this is not meant as an upgrade behavior and should probably be documented as such. People should use existing upgrade authoring - ideally implementing it in their package, especially for MSIs that support it natively.
