### ISSUE TITLE
Add winget package for winget

### ISSUE THREAD

**Issue by G0rocks** [microsoft/winget-pkgs#9593]
The point of adding this manifest is to be able to update winget using winget.

# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
PackageIdentifier:   Microsoft.Winget # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:     0.2.10771 Preview # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           Microsoft Corporation # publisher name (example: "Microsoft Corporation")
PackageName:         Winget # package name (example: "Windows Terminal")
License:             MIT # package license (example: "MIT")
ShortDescription:    Windows package manager # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```
