### ISSUE TITLE
[Package Issue]: Command link not created for MikeFarah.yq

### ISSUE THREAD

**Issue by mloskot** [microsoft/winget-pkgs#99059]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

`winget install --id MikeFarah.yq` is installed but there is no link created in `$env:USERPROFILE\AppData\Local\Microsoft\WinGet\Links` for the `yq` command.

### Steps to reproduce

1. `winget install --id MikeFarah.yq`
2. `dir "$env:USERPROFILE\AppData\Local\Microsoft\WinGet\Links\yq.exe"` cannot find path

### Actual behavior

No command link is created.

### Expected behavior

Command link created, like it is created for `winget install --id  stedolan.jq`

```
$ dir "$env:USERPROFILE\AppData\Local\Microsoft\WinGet\Links"
la---        15/02/2023     21:05        0   jq.exe
```

### Environment

```shell
Windows Package Manager (Preview) v1.5.441-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1344
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.441.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by mloskot** [comment]
I wonder if the issue is related to the fact `Commands` is at root level

https://github.com/microsoft/winget-pkgs/blob/4b5d734d7d063cf8d7e26a172f15783cbb5f38c6/manifests/m/MikeFarah/yq/4.30.8/MikeFarah.yq.installer.yaml#L8-L9

while for `jq` it is nested

https://github.com/microsoft/winget-pkgs/blob/155c885d38b047781367ff1314505ea2f2496bc3/manifests/s/stedolan/jq/1.6/stedolan.jq.installer.yaml#L6-L12

 
It looks like according to the https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.4.0/installer.md, `Commands` should be `Installers.Commands`.

**Comment by mloskot** [comment]
It looks like the `Commands:` at root is a bug in `YamlCreate.ps1`, as I've just run it to create manifest for the latest release of `yq` and it generated this:

```yaml
# Created with YamlCreate.ps1 v2.2.3 $debug=NVS1.CRLF.7-3-3.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: MikeFarah.yq
PackageVersion: 4.31.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- yq
ReleaseDate: 2023-03-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_windows_amd64.exe
  InstallerSha256: 150E84574AA3A5BBDAB46D0F5ABF13FE91568A72592E7D85E21F5AD0581A88F8
- Architecture: x86
  InstallerUrl: https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_windows_386.exe
  InstallerSha256: 744A9F6B2F1DB21E53B85033AF038B112F6324889C4A6C258E052053E1211597
ManifestType: installer
ManifestVersion: 1.4.0
```

I will manually correct that according to the schema.
